### ISSUE TITLE
Refactor LineChart.js into Functional Component

### ISSUE THREAD

**Issue by jeanetteobr** [RedHatInsights/tower-analytics-frontend#102]
Currently LineChart.js is a class based component. We would like to refactor this into a functional component that uses hooks. A good example of this is BaseChart.js in the src directory of the tower-analytics-frontend repo.

**Comment by brumik** [comment]
The `BaseChart` is not converted to a functional component, just wrapped into one (or at least on the master). @jeanetteobr should I change it to one?
