### ISSUE TITLE
Create Reusable Fetch Hook

### ISSUE THREAD

**Issue by jeanetteobr** [RedHatInsights/tower-analytics-frontend#105]
We would like to create a reusable fetch hook to use across components to reduce the amount of repeat code we have in our code base. Currently, when a container component needs to make a request to the API we use a custom fetchEndpoints method. 

The new reusable fetch hook should:
- Accept any number of APIs as an arguments
- Return the appropriate number of responses 
- Call getUser() method to authorize user token before request/response made
- STRETCH GOAL: hook will return certain booleans that the FE uses to dynamically render UI, e.i. isLoading, emptyState, etc.

**Comment by brumik** [comment]
Why is this not needed anymore? Or just closed because become stale?

**Comment by jeanetteobr** [comment]
This issue was created originally to give me an opportunity to become familiar with the codebase. However, this is not mission-critical and has become quite stale. There may still be a need for it -- we should discuss during grooming or planning.
