### ISSUE TITLE
Automation calculator crashes if the last template is hidden

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#109]
# Description

Kaboom!

![bug-ac](https://user-images.githubusercontent.com/44381/79155611-62423680-7d9f-11ea-98d8-756e2e42ee3d.gif)

# Validation

1. Go to https://ci.cloud.redhat.com/beta/ansible/automation-analytics/automation-calculator
2. Hide all the templates
3. It should show "no data"

**Comment by benthomasson** [comment]
Traceback:

<img width="481" alt="Screen Shot 2020-04-13 at 5 28 47 PM" src="https://user-images.githubusercontent.com/44381/79163042-45f8c680-7dac-11ea-8dc8-5d48ba928915.png">

**Comment by appuk** [comment]
Say no more! 🥇 
![Screen Shot 2020-04-23 at 11 22 57 AM](https://user-images.githubusercontent.com/11617351/80117174-d1185000-8554-11ea-8181-bcc01e9f0463.png)
