### ISSUE TITLE
[RFE] Replace the eye icon

### ISSUE THREAD

**Issue by appuk** [RedHatInsights/tower-analytics-frontend#112]
# Description
Currently, the eye icon is used to show/hide the stats of that template in the Automation time graph
![Screen Shot 2020-04-14 at 2 36 49 PM](https://user-images.githubusercontent.com/11617351/79261439-d216f680-7e5d-11ea-886e-d2eb815a273a.png)
but AFAIK, this icon is used to show/hide password/confidential information, hence it can be confusing for the user

Also, the purpose of the icon(to enable/disable the template from the graph) itself is not very clear

It would be great if we choose another icon that fits better in this scenario

**Comment by kialam** [comment]
cc @trahman73

**Comment by trahman73** [comment]
@kialam We could try fa-toggle-on and fa-toggle-off to see if that helps. (or just use actual toggles like we do for other charts)

**Comment by kialam** [comment]
Related #132

**Comment by appuk** [comment]
The toggle work great! Verified following functionality:

- shows/hides the template from the graph
- The total savings adjusts automatically
- Disables the text field
- The information icon still works fine

![Screen Shot 2020-04-22 at 5 19 17 PM](https://user-images.githubusercontent.com/11617351/80035307-cf4f7d80-84bd-11ea-89a6-a83e2b4c9821.png)
