### ISSUE TITLE
Incorrect title of Clusters dropdown on notifications page

### ISSUE THREAD

**Issue by appuk** [RedHatInsights/tower-analytics-frontend#113]
The title of the clusters dropdown is incorrect on the notifications page:
![Screen Shot 2020-04-15 at 4 53 14 PM](https://user-images.githubusercontent.com/11617351/79390928-943dcf00-7f3e-11ea-8b8c-af598e26365b.png)

It should be changed to 'Select cluster' similar to the one on Clusters Page
![Screen Shot 2020-04-15 at 4 53 03 PM](https://user-images.githubusercontent.com/11617351/79391001-b6cfe800-7f3e-11ea-894c-412f7b8967bd.png)

**Comment by kialam** [comment]
See PR #130

**Comment by appuk** [comment]
🎉 
![Screen Shot 2020-04-22 at 5 19 32 PM](https://user-images.githubusercontent.com/11617351/80035263-be067100-84bd-11ea-8acd-f26c2a41dc80.png)
