### ISSUE TITLE
Y Axis Labels Can Overflow on Automation Calculator Chart

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#120]
**Describe the bug**
Once very large numbers are introduced in the AA calculator, you can run into an issue where the y axis labels overflow (e.g. 5,000,000,000,000).

**To Reproduce**
1. Go to '/automation_calculator'
2. Enter in a large amount for Manual Cost field
3. Observe the Y axis labels start overflowing past a certain point

**Expected behavior**
The chart labels should support large numbers. Whether that be automatically adjusting the padding and width to respond to these updates or reformatting these large numbers into exponents (e.g. 5,000,000 becomes 5 x 10<sup>6</sup>).

**Screenshots**
<img width="226" alt="Screen Shot 2020-04-17 at 11 24 26 AM" src="https://user-images.githubusercontent.com/2293210/79585614-0b3da980-809e-11ea-9cfd-7415dc719feb.png">

**Comment by appuk** [comment]
Looks great! 🎉 
<img width="862" alt="Screen Shot 2020-04-21 at 4 45 49 PM" src="https://user-images.githubusercontent.com/11617351/79912152-947f1400-83ef-11ea-9106-4975ad997f71.png">
