### ISSUE TITLE
Dashboards should use job_explorer v1 API and link to job explorer page for more details

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#124]
# Description

Existing cluster/org pages would link to this **job explorer** page

E.g. chart showing 700 failed/300 successful, can point to this page with filter active (filter on state, and specific day)

E.g. top 5 templates can link to this page with `show all link` (group by template, taking other filter options set from the dashboard)

**Is your feature request related to a problem? Please describe.**
We can have one API used in job explorer page and then specific dashboards can also use this API, with specific filters set.

**Related PRs**

Depends on:
- [ ] https://github.com/RedHatInsights/tower-analytics-backend/pull/353

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-148
