### ISSUE TITLE
Replace select-boxes with multi select-boxes

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#125]
# Description

Replace select boxes with multiselect boxes 

Usable paternfly component could be: https://www.patternfly.org/v4/documentation/react/components/select#grouped-checkbox-input-with-filtering

**Is your feature request related to a problem? Please describe.**
As a customer I want to be able to filter multiple clusters/orgs/templates/statuses

**Mock up**

Add mock up here when ready

**Related PRs**

Depends on:
- [x] https://github.com/RedHatInsights/tower-analytics-backend/pull/353

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by brumik** [comment]
@Ladas Is this issue still actual? The link provided is not working anymore and there are not enough details to get what you want to change.

**Comment by Ladas** [comment]
@brumik no we can close this since we already have multiselect boxes
