### ISSUE TITLE
Job Explorer UI tabular view

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#127]
# Description

The initial release version of the Job Explorer feature encompasses the following details:
Using the new FastAPI backend `v1 api/job_explorer`
1. As an AA user I want to view a list of jobs.
![Screen Shot 2020-07-01 at 11 28 00 AM](https://user-images.githubusercontent.com/2293210/86263060-aec33400-bb8e-11ea-82ee-1cb0eb515a42.png)

2. As an AA user I want to view a list of jobs filtered by:

- Status
- Job Type
- Organization
- Templates
- Clusters
- Date
![Screen Shot 2020-07-01 at 11 28 06 AM](https://user-images.githubusercontent.com/2293210/86263049-a9fe8000-bb8e-11ea-8615-2f170396df51.png)

3. As an AA user I want to view a list of jobs sorted by various available attributes:
```
id, id:asc, id:desc, started, started:asc, started:desc, finished, finished:asc, finished:desc, elapsed, elapsed:asc, elapsed:desc, job_type, job_type:asc, job_type:desc, status, status:asc, status:desc, created, created:asc, created:desc, host_count, host_count:asc, host_count:desc, failed_host_count, failed_host_count:asc, failed_host_count:desc, failed_unreachable_host_count, failed_unreachable_host_count:asc, failed_unreachable_host_count:desc, host_task_changed_count, host_task_changed_count:asc, host_task_changed_count:desc, host_task_count, host_task_count:asc, host_task_count:desc, host_task_failed_count, host_task_failed_count:asc, host_task_failed_count:desc, host_task_ok_count, host_task_ok_count:asc, host_task_ok_count:desc, host_task_retry_count, host_task_retry_count:asc, host_task_retry_count:desc, host_task_skipped_count, host_task_skipped_count:asc, host_task_skipped_count:desc, host_task_unreachable_count, host_task_unreachable_count:asc, host_task_unreachable_count:desc, average_elapsed_per_host, average_elapsed_per_host:asc, average_elapsed_per_host:desc, average_host_task_count_per_host, average_host_task_count_per_host:asc, average_host_task_count_per_host:desc, average_host_task_ok_count_per_host, average_host_task_ok_count_per_host:asc, average_host_task_ok_count_per_host:desc, average_host_task_failed_count_per_host, average_host_task_failed_count_per_host:asc, average_host_task_failed_count_per_host:desc, average_host_task_unreachable_count_per_host, average_host_task_unreachable_count_per_host:asc, average_host_task_unreachable_count_per_host:desc, average_host_task_skipped_count_per_host, average_host_task_skipped_count_per_host:asc, average_host_task_skipped_count_per_host:desc, average_host_task_retry_count_per_host, average_host_task_retry_count_per_host:asc, average_host_task_retry_count_per_host:desc, average_host_task_changed_count_per_host, average_host_task_changed_count_per_host:asc, average_host_task_changed_count_per_host:desc, total_count, total_count:asc, total_count:desc
```
4. As an AA user I want to view a list of jobs and be able to paginate between results.
![je_pagination](https://user-images.githubusercontent.com/2293210/86262807-5be97c80-bb8e-11ea-9427-ab9c97f41d6f.png)

5. As an AA user I want to view a list of jobs and be able to ignore or include nested workflows and jobs.
![je_ignorewfandjobs](https://user-images.githubusercontent.com/2293210/86263104-c1d60400-bb8e-11ea-9427-e21ae3cdd6fd.png)

6. As an AA user, I want to be able to click on a point within the various charts (Bar Chart, Line Chart, Grouped Bar Chart) and see a list of jobs pertaining to that chart segment.
![click-throughs](https://user-images.githubusercontent.com/2293210/86263340-1aa59c80-bb8f-11ea-9c0c-b773694f11c5.gif)

7. As an AA user I want to be able to view a list of jobs and be able to expand to see more details on specific job.
![Screen Shot 2020-07-01 at 11 38 42 AM](https://user-images.githubusercontent.com/2293210/86263705-96074e00-bb8f-11ea-9977-6f676295c12f.png)

**Is your feature request related to a problem? Please describe.**

Customers are not being able to drill down

**Mock up**

https://tower-mockups.testing.ansible.com/examples/analytics/jobs/analytics-jobs/

**Related PRs**

Backend PR: https://github.com/RedHatInsights/tower-analytics-backend/pull/353
UI PR: #172
# Verification

**Steps**

Add verification steps here when ready for QE

**Comment by kialam** [comment]
Job explorer has been released so closing this ticket.
