### ISSUE TITLE
Expose query params in URL

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#128]
# Description
As we add more list views to our app with multiple filters and sort options, we need a way to preserve the user's selection history as they navigate throughout various sections of the app.

**Is your feature request related to a problem? Please describe.**
This feature would allow users to save specific urls/views as bookmarks and reference points.

**Describe the solution you'd like**
Configure React Router to update browser history as users navigate, toggle, interact with various knobs that control the query params of a view.

**Describe alternatives you've considered**

**Additional context**
Related #127, #124, 

**Mock up**

Add mock up here when ready

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by unlikelyzero** [comment]
@appuk when testing this, there is a string length limit to the length a url that is often smaller than the spec. The cloud.redhat.com team may have a better idea of what the realistic limit will be.

When projects/products implement this functionality, it's good to do an end-to-end test with the maximum number of characters allowed by a query filter, stacked with the max number of filters (plus some extra for future work).

**Comment by Ladas** [comment]
The limit is usually about 2000 chars. So it should work for our first try of filtering/bookmarking. (and there will be limits e.g. for how many multiselect items you can select)

As a second round, we'll need to move queries to POST from GET and utimately and we'll need to make the query filter saveable (although, we'll still limit what you can filter, since it affects query speed).

**Comment by unlikelyzero** [comment]
@Ladas thats the spec limit, but from my experiences there can be other limitations:

1. Some random nginx / tomcat config controlled by another team.
2. User Tracking Data can be appended (depending on the platform)

**Comment by Ladas** [comment]
@unlikelyzero btw. if we'll go with a path having all parameters after `#`, then this is purely browser issue, correct? Since anything after # shouldn't be sent to server (the actual parameters will be send via POST request)

So that is usual way of solving this (e.g. kibana and others do this)

**Comment by Ladas** [comment]
@kialam @jeanetteobr @benthomasson @bronaghs @jameswnl @AparnaKarve @unlikelyzero I am still not sure where do discuss if we change something in the API still. :-) 

This is the API example using POST for filters:
https://github.com/RedHatInsights/tower-analytics-backend/pull/353/files#diff-01963bb7191a6e399d529db848a57f0aR4

Pagination and sort_by must stay under GET, so we follow the IPP. So keeping the same filter POST body, we can use pagination ordering to browse the data.

Discuss. (there are not many way to do this, basically 1 way :-) E.g. kibana use this)
