### ISSUE TITLE
Improve wording for the Automation calculator UI

### ISSUE THREAD

**Issue by appuk** [RedHatInsights/tower-analytics-frontend#134]
This ticket tracks the changes in wording:

1. Automation Formula:
**Current text:** 
![Screen Shot 2020-04-22 at 5 27 32 PM](https://user-images.githubusercontent.com/11617351/80035772-949a1500-84be-11ea-8c1d-1e0fbc89f4b8.png)
**Proposed changes**
    - either remove unit from the entire formula
    - or insert units at all places

2. runs x hosts text
**Current text:**
![Screen Shot 2020-04-22 at 5 19 17 PM](https://user-images.githubusercontent.com/11617351/80035934-d9be4700-84be-11ea-9001-ce02b81af9ab.png)
**Proposed changes**
Maybe change the wording to clarify that the values are actually `successful_run_count` and `successful_host_run_count_avg`

@kialam feel free to fill in for - which change would be better

**Comment by brumik** [comment]
@appuk I am working on it so I would be happy to change the Automation formula text, but I don't see which 'units' you are referring to.

**Comment by appuk** [comment]
@brumik I was talking about `time for manual run on one host` text, it does not have any unit specification while all other values do
so recommended text would be `time for manual run on one host in hours`

**Comment by brumik** [comment]
I think since the filter will be visible (in the toolbar in form of chips) the second part of this issue is not relevant anymore.

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-150
