### ISSUE TITLE
Ensure all side nav uses consistent casing (was: "calculator" in left nav should be lower case)

### ISSUE THREAD

**Issue by cbudz** [RedHatInsights/tower-analytics-frontend#139]
**Describe the bug**
Automation Calculator field in left nav has second word capitalized and breaks conventions with other features on the automation platform. Sitting under "Organizational statistics" and breaking from that convention it looks off. 

For reference: https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology#capitalization

**To Reproduce**
1. Go to cloud.redhat.com
2. Click on Automation Analytics 
3. Scroll down to 'Automation Calculator

**Expected behavior**
Automation calculator (second word lower case)

**Comment by IPvSean** [comment]
![not sure](https://imgflip.com/s/meme/Futurama-Fry.jpg)

**Comment by kialam** [comment]
This is now deployed to CI and ready for verification. https://ci.cloud.redhat.com/beta/ansible/automation-analytics/clusters

**Comment by wenottingham** [comment]
This is live

**Comment by wenottingham** [comment]
... and it shouldn't be this, we are to use Title Case for navs.

@kialam will be submitting a patch to cloud-services-config for this

**Comment by wenottingham** [comment]
This is being handled on the PF4 chrome side. Moving to `needs_test`, to be tested with PF4 update.

**Comment by appuk** [comment]
The navigation looks good in CI and QA envs but not consistent on prod
![image](https://user-images.githubusercontent.com/11617351/91325884-b1f32e80-e791-11ea-8ed7-8fdd7efbbbf4.png)

@kialam do we need to submit a patch to cloud-services-config?

**Comment by appuk** [comment]
As per discussion offline, the fix is deployed in CI Beta and will get to Prod with the release 1.1.0
Hence closing the issue
