### ISSUE TITLE
Travis build setup and update README

### ISSUE THREAD

**Issue by brumik** [RedHatInsights/tower-analytics-frontend#146]
## Description Travis error

The Travis build is failing out of the box.  As only you (@kialam) made it work in the active PR's guess you will know why it is happening. (`docker_push` contains a `benthomasson/tower-analytics-frontend` string which is too specific I think and needs name and password.) 

[Edit]
It is happening because some secrets are not available on forked branches. It will work on branches from https://github.com/RedHatInsights/tower-analytics-frontend only. Thanks: @benthomasson 

_While at it: also `travis.config` has some warnings about missing values (deprecation)_

## Update README:

Since I just set up the development environment I know that the repo's readme is way off. After solving the Travis build problem I would like to update the readme to reflect how to set up the whole process. That would be beneficial for everybody I think.

**Comment by benthomasson** [comment]
This was fixed by #153
