### ISSUE TITLE
Upgrade to PatternFly4

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#151]
# Description

The C.R.C platform team wants all apps to upgrade to PatternFly4 by July 13th so they can upgrade the chrome to PatternFly4 then.

- [x] Test app with PatternFly4
- [x] Determine what changes need to be made
- [x] Make those changes
- [x] Verify changes

**Comment by benthomasson** [comment]
We are two major versions behind on two components of patternfly on one major version on the other. 

> -    "@patternfly/patternfly": "2.56.3",
> -    "@patternfly/react-core": "^3.134.1",
> -    "@patternfly/react-table": "2.10.0",
> +    "@patternfly/patternfly": "4.10.29",
> +    "@patternfly/react-core": "4.18.1",
> +    "@patternfly/react-table": "4.5.3",

**Comment by jctanner** [comment]
I believe this is complete?

```
[jtanner@corsair tower-analytics-frontend]$ fgrep patternfly package.json 
    "@patternfly/patternfly": "4.10.31",
    "@patternfly/react-core": "4.18.5",
    "@patternfly/react-table": "4.5.7",
```

**Comment by jeanetteobr** [comment]
@jctanner Correct! Deployment and testing for the PF4 upgrade on ci-beta is complete

**Comment by benthomasson** [comment]
This was completed by #156.

**Comment by benthomasson** [comment]
Jira issue: https://projects.engineering.redhat.com/browse/RHCLOUD-6958

**Comment by benthomasson** [comment]
I believe this has been tested already. Is that right @appuk?

**Comment by appuk** [comment]
We have one last Upgrade to the Prod Stable that is scheduled on 7/30
Can we close it when we complete that?

**Comment by appuk** [comment]
Verification for PF4 Upgrade completed on all environments, hence closing the issue
