### ISSUE TITLE
Add ids to components for visual regression testing

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#159]
# Description

Add ids to components for visual regression testing.  These items need ids:

* bars in bar charts
* links in the top templates

# Verification

There are id attributes on all the components that need to be select-able for visual regression testing.

**Comment by benthomasson** [comment]
@appuk please add to the list above with all the things that you'd like to have ids.

**Comment by unlikelyzero** [comment]
@benthomasson @appuk please sync with @psav on OUIA before adding IDs

**Comment by benthomasson** [comment]
@unlikelyzero add a new issue for OUIA support.

**Comment by unlikelyzero** [comment]
Ticket added here https://github.com/RedHatInsights/tower-analytics-frontend/issues/161

Note: the use of unique IDs is not incompatible with OUIA

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-151
