### ISSUE TITLE
Investigate the use of OUIA components in our use of Patternfly

### ISSUE THREAD

**Issue by unlikelyzero** [RedHatInsights/tower-analytics-frontend#161]
# Description

The Patternfly project has unified its effort to provide testability for UI components using the OUIA pattern. We should investigate what is necessary to add that support to our frontend (if any is necessary at all)

**Comment by benthomasson** [comment]
@unlikelyzero please add links to OUIA documentation and specifications.

**Comment by unlikelyzero** [comment]
Docs here
https://ouia.readthedocs.io/en/latest/

**Comment by jctanner** [comment]
I don't think we need two tickets tracking this concept.

https://github.com/RedHatInsights/tower-analytics-frontend/issues/159
