### ISSUE TITLE
vertically unaligned table headers

### ISSUE THREAD

**Issue by jctanner** [RedHatInsights/tower-analytics-frontend#166]
**Describe the bug**
Table headers are no longer vertically aligned

**To Reproduce**
1. Go to the Clusters view
2. Examine the table header for Top Templates and Top Modules

**Expected behavior**
All header cells should be vertically aligned

**Screenshots**

![Screenshot from 2020-06-17 17-07-11](https://user-images.githubusercontent.com/1869705/84950589-24be9a00-b0bd-11ea-8c55-8f7f4cde843d.png)

![Screenshot from 2020-06-17 17-08-36](https://user-images.githubusercontent.com/1869705/84950634-330cb600-b0bd-11ea-8fab-c6096d237a34.png)

![Screenshot from 2020-06-17 17-09-10](https://user-images.githubusercontent.com/1869705/84950684-47e94980-b0bd-11ea-93ff-89266ab6855e.png)

**Desktop (please complete the following information):**
 - OS: fedora 32
 - Browser chrome
 - Version 85.0.4158.4 (Official Build) dev (64-bit)

**Comment by jctanner** [comment]
I've reverted many of the last commits and manually bisected this down to the patternfly update: 1677446b0954b1509a530ee126758b6001ecdea0

**Comment by jctanner** [comment]
Maybe related to https://github.com/patternfly/patternfly-react/issues/4363

**Comment by benthomasson** [comment]
@AlexSCorey There might be an issue here where layers of wrapping components are missing.  Try adding in the missing wrapping components to see if it restores the padding without adding the styles in #168. 

https://www.patternfly.org/v4/documentation/react/components/datalist#examples

**Comment by appuk** [comment]
The headers are now aligned properly, hence closing 👍 
![image](https://user-images.githubusercontent.com/11617351/86948891-d6307880-c11b-11ea-8323-4b8c0001e40d.png)
