### ISSUE TITLE
Top Template Details in Modal Need Padding

### ISSUE THREAD

**Issue by jeanetteobr** [RedHatInsights/tower-analytics-frontend#167]
After the upgrade to PF 4.x, the details in the top templates modal no longer has padding and the headings of the modal data list are misaligned. 

1. Go to /Clusters 
2. Scroll down to Top Templates card
3. Click on a template name to surface details modal

**Expected behavior**
There should be padding of 24px around the template details.
![Screen Shot 2020-06-17 at 5 20 03 PM](https://user-images.githubusercontent.com/32466511/84951749-e2965800-b0be-11ea-8167-4587a90f4e38.png)

![Screen Shot 2020-06-18 at 4 26 43 PM](https://user-images.githubusercontent.com/32466511/85068504-8562db00-b180-11ea-80dc-930f751a4ace.png)

**Screenshots**
![Screen Shot 2020-06-17 at 5 10 26 PM](https://user-images.githubusercontent.com/32466511/84950846-7ebf5f80-b0bd-11ea-8c52-587680841034.png)

![Screenshot from 2020-06-17 17-09-10](https://user-images.githubusercontent.com/1869705/84950684-47e94980-b0bd-11ea-93ff-89266ab6855e.png)

**Desktop:**
 - OS: macOS Catalina
 - Browser Chrome
 - Version Version 81.0.4044.138

**Comment by appuk** [comment]
@jeanetteobr This issue seems to be fixed, can we go ahead and close this?
