### ISSUE TITLE
Add date filtering to the ROI calculator

### ISSUE THREAD

**Issue by wenottingham** [RedHatInsights/tower-analytics-frontend#173]
# Description

Currently, the ROI calculator shows the calculation across the entirety of data we have stored for the account.
Customers want to be able to show the ROI for a particular date range (most often, year to date, or for a particular month)

**Describe the solution you'd like**
The ROI calculator should use our standard date picking widgetry, and use that to query the API for the date range specified.
The API should already support these queries.

The date range should potentially have a default. One suggestion would be "year to date".

**Describe alternatives you've considered**
Alternatives would be hardcoded UI choices (year to date, last 30 days, last week). But if we have a standard date picker interaction model, and the API supports it, I don't see a reason not to just do arbitrary dates.

**Additional context**

**Mock up**

**Related PRs**

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by wenottingham** [comment]
Adding doc label as this may require a doc update .

**Comment by jctanner** [comment]
Should be able to find example code in the clusters or org stats components.

**Comment by jctanner** [comment]
reopen for testing

**Comment by benthomasson** [comment]
@jctanner please update the first comment with screenshots of the implementation and how to test it.

**Comment by appuk** [comment]
Verified that the Graph, Total savings and Top templates calculations render correctly on Changing the Date filter
I don't see any issues, hence closing
