### ISSUE TITLE
Link templates in ROI calculator to the job explorer

### ISSUE THREAD

**Issue by wenottingham** [RedHatInsights/tower-analytics-frontend#174]
# Description

Once the Job Explorer lands, we will be able to link to a view of all runs for a particular template.

The template names in the ROI calculator should link to the job explorer in this way.

**Describe alternatives you've considered**

**Additional context**

**Mock up**

Add mock up here when ready

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by wenottingham** [comment]
If there is enough dev/QE bandwidth for this to land with the job explorer, we should target 1.1.

**Comment by benthomasson** [comment]
@brumik which PRs are involved with this issue?

**Comment by brumik** [comment]
https://github.com/RedHatInsights/tower-analytics-frontend/pull/207

I miss linked the issue to the PR and didn't notice, sorry

**Comment by appuk** [comment]
Verified the feature by ensuring that:
 - The link correctly applies the filter of Job Template
 - Applies the date range of 30 days irrespective of date range selected
 - The number of runs for the template( in past month) on ROI matches with number of jobs shown in job explorer
 - Only shows successful jobs

This works as expected, hence closing
