### ISSUE TITLE
Link top templates to job explorer view

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#183]
# Description

Now that we have the new `v1/job_explorer` endpoint, we can now link the top templates to the job explorer list, filtered by `template_id`.

**Is your feature request related to a problem? Please describe.**
As an AA user, I'd like to click on a template name on the Top Templates section on the Clusters page and see a list of jobs filtered by the specific template.

**Describe the solution you'd like**
When a user clicks on a template in the Top Templates list (see Exhibit A) the user should should also see a "View all jobs" link that redirects them the job explorer page filtered by template (see Exhibit B).

[Exhibit A]
![view_all_jobs](https://user-images.githubusercontent.com/2293210/87099845-cd719c80-c218-11ea-9f51-230e8b9242ef.png)

[Exhibit B]
<img width="1792" alt="filter_by_template" src="https://user-images.githubusercontent.com/2293210/86970125-de4ce000-c13c-11ea-9bc7-f4853c7018c6.png">

Additionally, the top templates detail modal list can be refactored to use the new `v1/job_explorer` endpoint, ordered by most recent from the past month, returning the first 5 results, filtered by the specific template_id and job type of job.

The top templates detail modal aggregate stats box can be refactored to use the new `v1/job_explorer` endpoint by passing a `group_by: template` param which will then return (most) of the aggregate statistics.

This work should be branched off the job explorer feature branch - `jo_job-explorer-list-view`.

**Additional context**
@benthomasson @Ladas there appears to be a discrepancy in run count for the templates across views in our app. On the Clusters page the API is returning `total_run_count: 16` while on the Job Explorer page the total number of jobs is `48`. I _believe_ this is because the `/v0/template_jobs` is ignoring nested workflow jobs and jobs, and only returning `status: successful` jobs, thus `16` instead of `48`. Not sure how we want to handle this - should we pre-filter with those same parameters on the job explorer page or adjust the `v0/template_jobs` endpoint to return 48?

**Mock up**

Add mock up here when ready

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by Ladas** [comment]
@kialam so the v0_1 list of jobs uses filter:

Filters only `job_type: job` then specific cluster if set and last 30 days by default. Then the total count should be the same. If it's not, there might be a bug.


--------

Fo the header, you can get all the info except most_failed_tasks (will be working on that) if you will fire the same query just adding `group_by: template`, that should return 1 template record.

Then :
- total_time is `elapsed` (in seconds)
- number of runs is `total_count`
- success rate is `100 * successful_count / total_count`
- avg time is `elapsed/total_count`

**Comment by Ladas** [comment]
@kialam btw. I think @trahman73 was thinking about still having detail page for template (and probably for org and cluster too?) So alternatively we can keep this modal showing first 5 jobs and there would be a link `show all jobs` that would lead to job explorer with the active filter?

**Comment by benthomasson** [comment]
@appuk @brumik has this been tested in other issues?

**Comment by appuk** [comment]
@benthomasson Yes now that all open issue related to this feature are closed, this can be closed too
As part of this ticket, I verified:
 - The link applies the right filter of template and job status
 - If the Clusters page is filtered by Cluster or Date range, the same filter is also carried to the Job explorer page
 - The numbers on the Top Template modal and the Job explorer page match
