### ISSUE TITLE
Add a Top Workflows card to Clusters view

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#184]
# Description
Related https://github.com/RedHatInsights/tower-analytics-backend/issues/66
Add a Top Workflows card to the Clusters Dashboard.

**Is your feature request related to a problem? Please describe.**
As an AA user, I want to see a list of Top Workflows on the Clusters page.

**Additional context**

**Mock up**

https://tower-mockups.testing.ansible.com/analytics/dashboard/analytics/

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-152
