### ISSUE TITLE
ROI calculator doesn't scale vertically to fill window

### ISSUE THREAD

**Issue by wenottingham** [RedHatInsights/tower-analytics-frontend#189]
**Describe the bug**

![Screenshot from 2020-07-14 13-17-58](https://user-images.githubusercontent.com/5208768/87464006-65d49c00-c5e0-11ea-834e-759d7dd0a446.png)

Window size: 2560x1440. Scale: 80%

**Expected behavior**

Full vertical usage (esp of the scrollable top templates)

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Browser: Firefox
 - Version: 78.0.1

**Comment by wenottingham** [comment]
This is on beta with the pf4 upgrade, if that matters.

**Comment by appuk** [comment]
![image](https://user-images.githubusercontent.com/11617351/90423160-fdb72100-e089-11ea-93f3-ebb637ed28a6.png)
 the top templates is now scaling vertically to fill the window, hence closing the issue
