### ISSUE TITLE
Disable clicking on Others category

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#193]
**Describe the bug**
Right now the others category is represented with fake id -1, but that won't work for filtering of job explorer. Because the others can be always different. E.g. For 10 orgs selected in the orgs view, others are the other 5 orgs. But for 20 orgs selected others are the 15 orgs, etc.

So lets disable the link on others, until we figure out how to pass it. (maybe the API should support exclusion, so we can send `except_org_id=[1,2,3,4,5]`)

**To Reproduce**
1. Go to orgs page
2. Click on others
3. See error that no jobs are filtered, why the chart is showing some

**Expected behavior**

Ideally it will work. But for now we can disable the clicking.

**Screenshots**

![Screenshot from 2020-07-15 17-57-43](https://user-images.githubusercontent.com/1737058/87568265-aeb25080-c6c5-11ea-899b-51efe6de8e85.png)

![Screenshot from 2020-07-15 17-57-56](https://user-images.githubusercontent.com/1737058/87568269-b1ad4100-c6c5-11ea-9290-9ed78ccb350a.png)

**Comment by Ladas** [comment]
cc @kialam @appuk

**Comment by appuk** [comment]
clicking on the others tab is now disabled
before I close the issue, @Ladas is there another enhancement issue open to figure out how to pass all the organization ids in the others category?

**Comment by Ladas** [comment]
@appuk you can open the issue I think, or we'd open a generic issue for `not_in` operator. So e.g. you'll be able to do this in all `explorer` views and all dashboards

Each multiselect will have `.._operator` attribute. So e.g. to get a list of `Others` we'd pass `org_id_operator: 'not_in'` and `org_id: [ids we're currently showing]`
