### ISSUE TITLE
Others category should show over how many orgs it the statistics counted

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#194]
**Describe the bug**
On orgs page we show how many jobs/tasks are there for the other category, but we don;t say over how many orgs.

**To Reproduce**
1. Go orgs page
2. See `Others` across the page not showing how many orgs are in other category

**Expected behavior**

So e.g. we show: 

`Others: 123 jobs`

we should show

`Others: 123 jobs over 26 Organizations`

We can compute this from the API, the meta/counts returns e.g. `total_org_count: 31` so if we're showing 5 orgs, the others is across 31-5=26 organizations

**Screenshots**

![Screenshot from 2020-07-15 18-13-31](https://user-images.githubusercontent.com/1737058/87569585-a0fdca80-c6c7-11ea-8e38-7c45cc005033.png)

**Comment by Ladas** [comment]
cc @trahman73 @wenottingham

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-153
