### ISSUE TITLE
V1 API doesn't support appending [] to filter params

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#195]
**Describe the bug**
So e.g. if we sent filter `sort_by[]=id:asc` or `attributes[]='name'`, API will ignore it and fallback to default.

Because FastAPI is not able to parse this right and it takes `sort_by[]` as the name of the param. So all params must be send without `[]` suffix

**To Reproduce**
1. Go to job explorer
2. Sort by something
3. See it doesn't work and always sorts by `created` date, because we send `sort_by[]` and sort_by values are the default, because we send `attributes[]` to options filter

**Expected behavior**
Sending filters as `sort_by` and `attributes` the sorting will start to work properly.

**Screenshots**

![Screenshot from 2020-07-15 18-58-14](https://user-images.githubusercontent.com/1737058/87573435-2fc11600-c6cd-11ea-91ca-92b3a4812ef4.png)

**Comment by Ladas** [comment]
cc @kialam

**Comment by brumik** [comment]
@Ladas As I tried and understood: non of the filters supports `[]`? By removing all the braces from the URL I got a fully working API. Is that right?

Example old:
`https://prod.foo.redhat.com:1337/beta/ansible/automation-analytics/job-explorer?attributes[]=id&attributes[]=status&attributes[]=job_type&attributes[]=started&attributes[]=finished&attributes[]=elapsed&attributes[]=created&attributes[]=cluster_name&attributes[]=org_name&attributes[]=most_failed_tasks&limit=5&job_type[]=job&job_type[]=workflowjob&status[]=successful&status[]=failed&status[]=running&only_root_workflows_and_standalone_jobs=false`

Example new:
`https://prod.foo.redhat.com:1337/beta/ansible/automation-analytics/job-explorer?attributes=id&attributes=status&attributes=job_type&attributes=started&attributes=finished&attributes=elapsed&attributes=created&attributes=cluster_name&attributes=org_name&attributes=most_failed_tasks&limit=5&offset=1795&job_type=job&job_type=workflowjob&status=successful&status=running&only_root_workflows_and_standalone_jobs=false`

Did you mean like this?

**Comment by Ladas** [comment]
@brumik right, that would be if you'd use GET, then yeah it needs to be e.g. `attributes=status&attributes=job_type`, if you use  `attributes[]=status&attributes[]=job_type`, FastAPI will think the attr name is `attributes[]` and will ignore it

Currently @kialam uses POST and the attributes sent via post seems to be ok. But we send `sort_by, limit, offset` always via get, so `sort_by` is broken in current UI

Also we can switch the `_options` call to POST and also only fix the sort_by

**Comment by brumik** [comment]
@Ladas I looked at it, and I think fixin' just the sort_by would be easier. 

Just one question: sort_by then does not support multiple values right? Because right now we have a multiselect there and will try to send an array of selected items to sort_by.

**Comment by Ladas** [comment]
@brumik yeah, sort_by is simple select. 

If we'd want to sort_by multiple cols, we'd have to figure out how to order them.

**Comment by appuk** [comment]
I will test the sorting feature separately, but looks like it is working, and the issue mentioned above is no more present, hence closing the issue
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/11617351/91094708-2eb6c900-e629-11ea-8810-d1d5d2fe606c.gif)
