### ISSUE TITLE
How to represent default selected filters as tags in job explorer

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#196]
# Description

Some of the filters do have default values (that can change based on selection). So we should figure out how to present these to users.

E.g. by default we order by `created:desc` and filter `last_30_days` for job explorer_job list

Once we are able to group by (e.g. group by template) and use granularity, that will switch the default values. So e.g. grouping by `template` and switching to `monthly` granularity, we'll switch to default: 
order by `total_count:desc` (total number of jobs)
and `last_3_months`

**Is your feature request related to a problem? Please describe.**
It's not clear what is a default selection of some filters, like time filters and sort_by 

So e.g. in this screenshot, I should see it's sorted by default by `created:desc` showing me last 30 days of data

![Screenshot from 2020-07-17 18-09-38](https://user-images.githubusercontent.com/1737058/87807672-d554c080-c858-11ea-89f9-3614e9d21790.png)

**Describe the solution you'd like**
We should probably show default values as greyed out tag? (having title description it's a default value) (We can't really remove it, since it's default, but we can select something else for e.g. sort_by, but by removing the tag it will jump back to default)

**Mock up**

Add mock up here when ready

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by Ladas** [comment]
discuss @kialam @trahman73 @wenottingham

**Comment by wenottingham** [comment]
For ordering, wouldn't the expected UX be that it's ordered by one of the columns, and that's how it's shown to the user? i.e., ordering is determined by the UI, not the API return.

If it's date ranged by default, that should definitely show in the filter.

**Comment by trahman73** [comment]
I would recommend default view to be ID/Name descending. I would also not show the search tags for a default view until the user customized the filter themselves.

**Comment by Ladas** [comment]
@trahman73 @wenottingham so I'd expect the default ordering to show latest jobs? So that should be either created or finished timestamp.

ID is tricky for multi-cluster, for one cluster, ordering by ID is basically the same as created timestamp (so that works nicely for tower). But for multi-cluster the biggest cluster will overshadow the smaller. Since e.g. biggest will have IDs around 100k and small around 10k, you'll see just biggest cluster's jobs and no new small cluster's jobs.

**Comment by Ladas** [comment]
@trahman73 btw. you were sending the new design for `sort_by` somewhere, can you put it here? I think that solves the default value presentation? And maybe in a similar way the time range filter would be always visible (somewhere on the right side maybe?)

It is basically just the sort_by and date range filter that must have some default value. (for aggregations it will also be granularity, that can be next to date range filter -> daily/monthly/yearly)

**Comment by trahman73** [comment]
@Ladas Here is an example of the Sorting being pulled out on it's own. We can pull out the date filter in a similar way. I have suggested to Kia to move the workflow jobs toggle to a Settings dropdown to generate some more space.
![image](https://user-images.githubusercontent.com/13351591/87995752-5e206600-cabe-11ea-8bcc-59bb907736f6.png)

**Comment by appuk** [comment]
As per the discussion offline, this is a good enough solution for now
Moving the date filtering and sorting options out of the filter tags(which will tentatively be part of 1.1.1) will solve all the UX related issues
Hence closing this issue
