### ISSUE TITLE
Org view can't toggle Organization not set with null error

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#198]
**Describe the bug**
 When clicking on toggle `Organization not set`, I am not able to toggle it in the org chart. It throws null error in console.

**To Reproduce**
1. Orgs page
2. Click on toggle button on `Organization not set`
3. See it doesn't toggle with error in browser console

**Expected behavior**
it should toggle

**Screenshots**
![Screenshot from 2020-07-20 10-14-53](https://user-images.githubusercontent.com/1737058/87915289-41f6d780-ca72-11ea-9de4-cf7ba28553bb.png)

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [latest on fedora 32]

**Comment by Ladas** [comment]
cc @kialam @appuk

**Comment by kialam** [comment]
@Ladas this is an API issue as it currently returns an ID of `null`.

**Comment by Ladas** [comment]
@kialam I see, I'll make it consistent with `v1` return value

**Comment by Ladas** [comment]
@kialam cool, that was it, fixed by https://github.com/RedHatInsights/tower-analytics-backend/pull/397 commit https://github.com/RedHatInsights/tower-analytics-backend/pull/397/commits/e5c9c1c4aef564f3f9a9b4bcf730eae17764f130
