### ISSUE TITLE
Switch to V1 API - ROI

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#199]
# Description

Switching ROI to v1 API so we can use the master filter we're using in job explorer

Talking to @kialam , this might be easiest view to switch.

Query to mimic v0_1 API result:
-------------------------------------------

```
curl -X GET "http://localhost:8004/api/tower-analytics/v1/job_explorer/?quick_date_range=last_30_days&only_root_workflows_and_standalone_jobs=true&limit=5&sort_by=host_count%3Adesc&group_by=template&group_by_time=false&granularity=monthly&status=successful&attributes=elapsed&attributes=host_count&attributes=host_task_count&attributes=total_count&attributes=total_org_count&attributes=total_cluster_count" -H "accept: application/json"
```
params:
- granularity=monthly & quick_date_range=last_30_days
We can use monthly granularity by default (so we can pick 1-18 months), uquick date ranges should be based on https://github.com/RedHatInsights/tower-analytics-backend/issues/461

- only_root_workflows_and_standalone_jobs=true
If we'll be showing both workflows and jobs, we need this set to avoid duplicates (we'd show savings of individual templates and duplicate when part of workflows)

If we don't want to expose this to user, we can set it this way to avoid duplicates:
```
if job_type includes workflowjob, set only_root_workflows_and_standalone_jobs=true
else set only_root_workflows_and_standalone_jobs=false
```

- status=successful
ROI focuses only on successful runs

- attributes:
```
attributes=elapsed # total_elapsed, since we filter successful, this is successful_elapsed
attributes=host_count # total host runs for all jobs, host_count/total_count == avg hosts per job run
attributes=host_task_count # total amount of tasks run across all jobs and hosts
attributes=total_count # total count of job runs, since we filter successful, it's amount of successful job runs
attributes=total_org_count # on how many orgs were the job being run
attributes=total_cluster_count # on how many clusters were the jobs being run
```

example result:
```
{
  "response_type": "jobs_by_template",
  "items": [
    {
      "elapsed": 1039.5,
      "host_count": 4400,
      "host_task_count": 9520,
      "total_count": 177,
      "total_org_count": 2,
      "total_cluster_count": 2,
      "id": 2,
      "name": "template_name_0"
    },
    {
      "elapsed": 105.7,
      "host_count": 1400,
      "host_task_count": 3520,
      "total_count": 18,
      "total_org_count": 2,
      "total_cluster_count": 1,
      "id": 55,
      "name": "template_name_3"
    },
    {
      "elapsed": 105.7,
      "host_count": 1760,
      "host_task_count": 3520,
      "total_count": 18,
      "total_org_count": 2,
      "total_cluster_count": 1,
      "id": 52,
      "name": "template_name_9"
    },
    {
      "elapsed": 105.7,
      "host_count": 1760,
      "host_task_count": 3520,
      "total_count": 18,
      "total_org_count": 2,
      "total_cluster_count": 1,
      "id": 7,
      "name": "template_name_6"
    },
    {
      "elapsed": 99.8,
      "host_count": 680,
      "host_task_count": 1360,
      "total_count": 17,
      "total_org_count": 2,
      "total_cluster_count": 1,
      "id": 3,
      "name": "template_name_1"
    }
  ],
  "meta": {
    "count": 60
  },
```

What we lack vs. v0_1 API:
--------------------------------

The API returns the same data we need for the main calculation (the chart), so the differences are in the extra info we show on hover of `i` icon

1. We don't return successful elapsed vs. failed elapsed time, since we just filter `status: successful`. Users will be able to drilldown into these once we allow `group_by: template` in job explorer or we do a template detail page (we will need to do design for this, we just had a short talk with @trahman73 ) 

2. We don't return automation percentage, but we can compute it from total_elapsed or total_host_count in `meta`

3. We don't return names of clusters and orgs, just a number. Talking to @trahman73 this doesn't scale anyway, so once we have job explorer group by cluster/org, the number `Across 40 orgs/clusters` can lead to job explorer showing a paginated list of orgs/clusters

What we get extra vs. v0_1 API
------------------------------------------

1. Filtering consistent with job explorer (following `I can filter my prod env` story)

2. Showing ROI of workflows along with standalone templates (workflow has elapsed time and host runs of all templates inside), we must use `only_root_workflows_and_standalone_jobs=true` to avoid duplicate ROI

3. We can use `host_task_count` (how many tasks were run across all hosts) to better estimate default manual time needed per 1 host

**Is your feature request related to a problem? Please describe.**
Customers can't filter ROI of their production (or any part of it). Filtering capabilities should be consistent across the app.

**Describe the solution you'd like**
We should use v1 api described above with master filter being prepared in ob explorer (or subset of it)

**Describe alternatives you've considered**
None, we can do specific ROI endpoint using the new rollups if needed (e.g. once we store the times/prices in our DB)

**Additional context**

**Mock up**

Design doesn't change

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by Ladas** [comment]
cc @kialam @trahman73 @wenottingham

**Comment by AparnaKarve** [comment]
ROI payload for reference -
```
    {
            "template_id": 9,
            "name": "centos_security_updates",
            "run_count": 4,
            "failed_run_count": 2,
            "successful_run_count": 2,
            "elapsed_sum": 174.985,
            "failed_elapsed_sum": 36.921,
            "successful_elapsed_sum": 138.064,
            "host_run_count": 7,
            "failed_host_run_count": 4,
            "successful_host_run_count": 3,
            "orgs": [
                {
                    "org_id": 3,
                    "org_name": "Default"
                }
            ],
            "clusters": [
                {
                    "cluster_id": 1,
                    "cluster_name": "towerhost"
                }
            ],
            "host_run_count_avg": 2,
            "failed_host_run_count_avg": 2,
            "successful_host_run_count_avg": 2,
            "template_automation_percentage": 6.93166488183726,
            "cumulative_automation_percentage": 94.5279791463645,
            "known_roi_metric": 4
    }
```

We need the below corrections in the `What we lack vs. v0_1 API` section described above in https://github.com/RedHatInsights/tower-analytics-frontend/issues/199#issue-662827441


1. > We don't return successful elapsed vs. failed elapsed time

We return both successful and failed elapsed sum. We display these stats in the 'i' icon

2. > We don't return automation percentage,

We return `template_automation_percentage` and `cumulative_automation_percentage`. We display `template_automation_percentage` in the 'i' icon

3. > We don't return names of clusters and orgs, just a number.

We return both name and id of clusters and orgs. We display the cluster and org names in the 'i' icon

------

Also, for the manual time estimate, I think the module itself (task_action) is a better indicator than `host_task_count` (how many tasks were run across all hosts)
Reason being, the manual implementation equivalent of a playbook task may have a completely different style of execution or a completely different MO; so the module (what the module does) is our best bet to get an estimate.
We could possibly resort to `host_task_count` for custom modules (modules developed by customers)

**Comment by Ladas** [comment]
@AparnaKarve right the `What we lack vs. v0_1 API` means that we don't return these things in current v1 API. So my description is correct and your description is correct from the other side :-)

-----

Hm, diving into modules might be next thing, but it'll be kind of impossible to estimate this or to get a person to estimate this. Given how many modules are there and that the usage is always different. E.g. using `aws_ec2` module, it's more work to provision vms than e.g. just stopping the instances and these operations use the same module.

So right now our best shot is, how many tasks you did. So our defaults should be different to playbook running 1 task (like stop vm), vs. playbook running 10 tasks (provision vm, install db, configure db, etc.)  

Then later, we could add `weight` to this formula, depending on what module is under task. E.g. we'd say it takes 3s for task on avg. But e.g. for `debug` module we'd add weight 0.5 (so 3*0.5=1.5s for debug), etc. It might make sense to do this for some modules.

**Comment by benthomasson** [comment]
Instead of pushing all this work into the UI we should produce a new endpoint that is rewritten to use the job explorer on the API side.

**Comment by Ladas** [comment]
@benthomasson afaik there is no work? The formula is being computed on UI side and that stays.

Then we only miss `What we lack vs. v0_1 API` , where I think we should't show 

1), we should filter by `successful jobs` and just show that.
Otherwise we're showing e.g. ROI for successful, but list of orgs across all jobs. Also then the formula will be correct, since we say we compute with total elapsed, while in reality we take successful?

The failed/successful distribution (and distribution of host states and task states) should be in another section, like the template detail or the template perf improvement

2) Easy to compute in UI if needed
3) Needs to happen, since putting 40 orgs/clusters in hover doesn't scale, we have customers with 16 clusters and 67 orgs. And we should avoid doing `list all` anywhere.

---

That being said I can easily add 1) and 2) into existing API and 3) should be solved as described

**Comment by AparnaKarve** [comment]
@Ladas Not sure I entirely understand your points above.

With regards to `What we lack vs. v0_1 API` -

- With your API example above, we are missing some vital information like `successful elapsed`, which is key to ROI calculation.
- We are also missing Cluster and Organization names, which will be crucial for filtering (feature requested in #252)

So there is some work needed with job explorer and the rollup tables to be able to get that info.

The `job explorer` API's primary focus is `jobs` whereas the `ROI Templates explorer` (if you will) will focus on the ROI aspect of the templates, so I imagine there woud be many many differences. Meaning, we will need a separate dedicated API for ROI Templates explorer.

**Comment by jeanetteobr** [comment]
@Ladas @benthomasson Looking for some clarity on which endpoint the ROI needs to point to in order to utilize V1 of the API. It's my understanding that the job explorer endpoint should be used on the ROI calculator, however, we would be missing some vital data needed for accurate calculations on the FE. Let me know if the FE work needs to be put on hold for the time being until the API is ready.

**Comment by AparnaKarve** [comment]
@Ladas Could we add all the missing attributes for ROI as shown in the changes below?

https://github.com/RedHatInsights/tower-analytics-backend/compare/master...AparnaKarve:add_attribs_for_roi?expand=1
(missing attributes: `successful_elapsed_sum` and `failed_elapsed_sum` have been added here)

It would be a really good design if we create ROI-specific structures like `ROI_EXPLORER_ENTITY_AGGREGATES_ATTRIBUTES` and thus have a clear-cut distinction between the ROI-specific attributes and the JobExplorer-specific attributes.

The ROI-specific structures would be then used by the v1 ROI API.

I can work on a PR that adds all the missing ROI attributes. Let me know.

**Comment by Ladas** [comment]
@jeanetteobr  @AparnaKarve if we filter by `successful` job state, then `elapsed` is the successful elapsed, so nothing vital for the main calculation is missing? (and then everything is correctly filtered by the successful state we want to focus on, e.g. list of clusters and orgs too?)

@AparnaKarve the filtering works regardless of those org/cluster names. To get names of the orgs associated with the template, we have now the number that will be a link e.g. `60 orgs associated` and there is another job explorer query that gives paginated list of these orgs.

@AparnaKarve right now, there is nothing ROI specific (we're asking job explorer API for template usage statistics). It will make sense to start the ROI specific v1 API when we'll be implementing the design with prices in it. (and e.g. sorting by templates with biggest $ ROI) I know you've started the v0_1 API for it, but not sure if it's for 1.2? I think current focus is the filtering.

@benthomasson @jeanetteobr @AparnaKarve looks like there is still some confusion, so best would be to just jump into a call and got through the API attributes needed for the main calculation

**Comment by Ladas** [comment]
@wenottingham btw. we're getting the host states according to tower now, so it might make sense to focus on `changed hosts` for ROI? And if we'd look also at failed jobs, we can get changed hosts from those too. (along with other states)

So a normal workflow:
run template on 1000 hosts -> 3 failed, rest successful and changed [job failed]
(tweaking stuff) -> re-run template on 3 failed hosts -> 3 successful and changed [job successful]

So we'd correctly report ROI on 1000 configured hosts, not just on 3 hosts.

----

We can just allow people to filter by `job_state`, so default filter would look on `successful` jobs (so giving the same numbers like now), but if I'd want to get ROI on all changed hosts, I could filter `successful + failed` (cancelled and error probably don't make sense)


And we can maybe let people choose which host count to take? So any of (ok_hosts, changed_hosts, skipped_hosts) make sense. I'd say the `changed_hosts` makes the most sense?

**Comment by wenottingham** [comment]
Thinking... you either want (ok + changed) - all hosts where the automation applied successfully or just 'changed' - all hosts where the automation did something.

Think of config remediation - you still want to note the hosts that didn't need changed, as that's still "work" that would be done manually to confirm they're properly configured.

**Comment by AparnaKarve** [comment]
> right now, there is nothing ROI specific (we're asking job explorer API for template usage statistics). It will make sense to start the ROI specific v1 API when we'll be implementing the design with prices in it. (and e.g. sorting by templates with biggest $ ROI) I know you've started the v0_1 API for it, but not sure if it's for 1.2? I think a current focus is the filtering.

@Ladas Well, the way I look at it is, trying to fit ROI implementation in the JobExplorer mould, seems like a temporary workaround - since there is missing data - and understandably so - Job Explorer API is about jobs, and ROI API should be about ROI. 
Agreed, right now in the ROI API there are attributes that are somewhat generic and not strictly pertaining to ROI per se, but that is going to change soon - the moment we have information on Cost and Time details per tenant (which will be in 1.2), the doors are going to open for a lot more analytical data for viewing ROI in different types of lens (more filtering and sorting options, that is)

**Comment by AparnaKarve** [comment]
> To get names of the orgs associated with the template, we have now the number that will be a link e.g. 60 orgs associated and there is another job explorer query that gives paginated list of these orgs.

Ok, that would work.
The link to [60 Orgs](_blank) should be preferably inside the expanded Accordion though, where we show more info.

To keep the UI/UX  consistent across the app, the top level filter for Organizations (like in Job Explorer, shown below) should also be available 

<img width="332" alt="Screen Shot 2020-09-04 at 2 24 53 PM" src="https://user-images.githubusercontent.com/1538216/92285971-8e7b6280-eeba-11ea-8a5a-3f307f3dc465.png">

**Comment by AparnaKarve** [comment]
> if we filter by successful job state, then elapsed is the successful elapsed, so nothing vital for the main calculation is missing? (and then everything is correctly filtered by the successful state we want to focus on, e.g. list of clusters and orgs too?)

Would have been nice if we could query for both `successful` and `failed` in 1 API request.

`failed elapsed` is not used in calculations today, but it just contributes towards a more holistic view on the state of the template.

**Comment by Ladas** [comment]
@AparnaKarve yeah, the filtering should be consistent across the app (following the customer story: I want to filter my prod env)

As you say, right now ROI backend is not really ROI. So the current job_explorer API is enough for make the filtering work. The v1 ROI API should be designed the same way, just extending what you can filter, sort_by etc. So we can easily use the same filter component (and open way to saving filters, etc.) And we can easily switch from v1 job explorer API to v1 ROI

----

I'd just remove the failed elapsed for now, since we don't show anything about it (the distribution of failure, e.g. 99% of hosts can be configured correctly there). And it's confusing the formula, since the formula says is computed with total elapsed time, while we're taking just successful elapsed. 

Also as mentioned ^, should be better to allow user to filter successful and optionally failed, to see ROI of that and as @wenottingham says above, we can focus on (ok + changed) hosts. And we can get these hosts across all filtered jobs.

So we can just be taking total elapsed of what you filter (successful, failed, successful+failed) and focusing on (ok + changed) hosts

**Comment by AparnaKarve** [comment]
@Ladas We can definitely reuse code from job explorer.

However, the ROI v1 API needs to be a distinct API (separate from job explorer API) and will have very specific ROI attributes like -
- Automation and Manual cost
- Manual Time
- RBAC permissions

**Comment by FleebSteve** [comment]
> @Ladas Could we add all the missing attributes for ROI as shown in the changes below?
> 
> https://github.com/RedHatInsights/tower-analytics-backend/compare/master...AparnaKarve:add_attribs_for_roi?expand=1
> (missing attributes: `successful_elapsed_sum` and `failed_elapsed_sum` have been added here)
> 
> It would be a really good design if we create ROI-specific structures like `ROI_EXPLORER_ENTITY_AGGREGATES_ATTRIBUTES` and thus have a clear-cut distinction between the ROI-specific attributes and the JobExplorer-specific attributes.
> 
> The ROI-specific structures would be then used by the v1 ROI API.
> 
> I can work on a PR that adds all the missing ROI attributes. Let me know.

I cannot access the tower-analytics-backend repository. Is it private on purpose? The rest of RedHatInsights repos seems to public.

**Comment by Ladas** [comment]
@AparnaKarve yeah, I think just because of the RBAC, it needs the separate endpoint (RBAC for being able to see $ cost and other ROI related attrs )

But implementation wise, we'd just use the explorer's common code (`records_grouped_by_entity`), adding the 2+ new attributes and joins and limiting attributes we can query from the new endpoint.

So that means we can integrate with job explorer now, to make the filtering work and moving to v1 ROI will be very easy (changing endpoint, querying more `attributes` and changing `sort_by`) and the filtering will still be working.

(And then on UI side more work with the prices management and using the API values for the formula. But that is new work anyway)

**Comment by Ladas** [comment]
@FleebSteve yeah it's private on purpose now. The API documentation should be published in a release or 2 in https://cloud.redhat.com/docs/api

**Comment by jeanetteobr** [comment]
@brumik Thanks for taking this over! :)

**Comment by brumik** [comment]
Waiting for #307

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-154
