### ISSUE TITLE
Switch to V1 for all APIs used

### ISSUE THREAD

**Issue by wenottingham** [RedHatInsights/tower-analytics-frontend#200]
# Description

We want to, over time, move views to the new V1 API.

- [ ] ROI (https://github.com/RedHatInsights/tower-analytics-frontend/issues/199)
- [x] authorized
- [ ] orgs dashboard [jobs_by_date_and_org_30, job_events_by_org_30, job_runs_by_org_30, hosts_by_org] (https://github.com/RedHatInsights/tower-analytics-frontend/issues/240 at best uses chart component: https://github.com/RedHatInsights/tower-analytics-frontend/issues/221)
- [ ] clusters dashboard [chart30, templates, template_jobs, modules] (https://github.com/RedHatInsights/tower-analytics-frontend/issues/239 at best uses chart component: https://github.com/RedHatInsights/tower-analytics-frontend/issues/220)
- [x] clusters (done, list of clusters is exposed in the _options API, same as other filter options)

Notifications will be done later, given we plan notifications overhaul,

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by benthomasson** [comment]
@Ladas Are you intending that all APIs the limited set of routes in V1 instead of the specific in v0?

**Comment by jctanner** [comment]
per @benthomasson, the first step is to switch to v0 routes: `/api/tower-analytics/v0/clusters/`

**Comment by Ladas** [comment]
@benthomasson yes, that way all dashboards can do the same filtering (we can use the same master filter)

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-156
