### ISSUE TITLE
Handle 422 validation error nicely

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#204]
**Describe the bug**
If we send invalid params into the API, it returns 422 code and we should print the error message to user

Right now the only case should be if we filter bigger date interval than max (max is 62 days)

**To Reproduce**
1. Go to job explorer
2. Click on date filter and select custom
3. Select from date to be 3 months ago (the distance between dates must be more than 62 days)
4. See table loading indefinitely

**Expected behavior**
A message from the API should be displayed, saying max 62 days can be filtered

**Screenshots**
![Screenshot from 2020-07-24 10-25-42](https://user-images.githubusercontent.com/1737058/88373758-b5f9ee00-cd98-11ea-9feb-39fd98fe3837.png)

**Comment by brumik** [comment]
@Ladas Is there any more specification for "nicely" displaying the info?
Also, in this case, I think we should limit the calendar's selection range to 62 days (if it is possible).

**Comment by Ladas** [comment]
@brumik riight, I am not really UX expert on what is nicely presented. @trahman73 is that ^ ok? Or should it be popup?

Yeah, so ideally we'd limit what you can select or we'd show you a popup with `You can select max 62 days with this precission, do you want to switch to 'monthly'  precision to display this range? (yes) (back)` . Or something in this sense. Not sure what is the right UX, but we should guide the user.

**Comment by brumik** [comment]
I wasn't sure who else ask, but thanks for the mention ^. I was thinking about just showing 62 days and give an extra line there, that the displayed items are for 62 days as it is the maximum available.

**Comment by trahman73** [comment]
@brumik @Ladas I agree that we should limit the actual selection but here is the PF alert example we would use.
![image](https://user-images.githubusercontent.com/13351591/88808899-70b33300-d181-11ea-884b-3c69e1958b54.png)

**Comment by appuk** [comment]
I see the validation error  as expected
![image](https://user-images.githubusercontent.com/11617351/91064109-d669d200-e5fc-11ea-8756-c36bf82ea625.png)

@brumik any specific reason we did not go ahead with the PF alert modal?

**Comment by brumik** [comment]
Yes, we had a discussion about it with @trahman73 . In short the problem with modal: what should be displayed after closing it.

**Comment by appuk** [comment]
Ahh makes sense, closing as verified
