### ISSUE TITLE
Max pagination limit for job explorer is 25

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#205]
**Describe the bug**
Sending limit more than 25 to job explorer API will throw 422, so lets have 25 as max in UI

**To Reproduce**
1. Go job explorer page
2. Change limit of pagination to 100
3. See API returning 422 and table area loading indefinitely

**Expected behavior**
We should offer max 25 records per page

**Screenshots**
![Screenshot from 2020-07-24 10-40-00](https://user-images.githubusercontent.com/1737058/88374433-0d4c8e00-cd9a-11ea-84f7-512f115afed7.png)

**Comment by jameswnl** [comment]
So this could be a separate issue: UI is not catching exceptions coming from promise and hence causing UI hanging at `Loading ....`.  The javascript console shows
```
:1337/ansible/automa…date_range=custom:1 Uncaught (in promise) 
{error: "Parameter limit must be in interval: <0, 25>, got: 50"}
error: "Parameter limit must be in interval: <0, 25>, got: 50"
__proto__: Object

```

I.e. API does report error clearly but UI is not handling it.

**Comment by Ladas** [comment]
@jameswnl   yeah, we need the nice handling for date ranges, described here https://github.com/RedHatInsights/tower-analytics-frontend/issues/204

**Comment by appuk** [comment]
The maximum pagination limit for job_explorer in UI is 25, hence closing
![image](https://user-images.githubusercontent.com/11617351/91059388-a4a23c80-e5f7-11ea-97e7-2dc060c6d871.png)
