### ISSUE TITLE
Job expoler's date range picker not working after custom date

### ISSUE THREAD

**Issue by brumik** [RedHatInsights/tower-analytics-frontend#209]
**Describe the bug**
When selecting a custom date in the filter then trying to select a predefined range (eg. Last 30 days, Last week, ...) the items are not changed - the filter ignores the change.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `Job Explorer`
2. Click on `Filter -> by date -> custom`,
3. Select a custom date (for example 50 days)
4. Click on `Filter -> by date -> Last week`
5. The shown items are not changed

**Expected behaviour**
The filter should change the displayed items accordingly

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Browser: Chrome
 - Version: 84

**Comment by appuk** [comment]
Verified this issue with following steps, working as expected:
1. Filter by Custom date
2. Filter by Last week
3. Filter for last week is applied successfully
Hence closing
