### ISSUE TITLE
Support the browser's back button on job explorer links

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#217]
**Describe the bug**

On the jo_job-explorer-list-view branch:

When clicking through to the job explorer it requires multiple clicks of the browser's back button to get back to the previous page.

**To Reproduce**
1. Go to clusters page
2. Click on a bar
3. Click on the browser's back button until the previous page is reached.  It takes me about 4 clicks.

**Expected behavior**
It should only take a single click to get back to the previous page.

**Screenshots**

![job_explorer_back_button](https://user-images.githubusercontent.com/44381/89225142-bddf3c80-d5a7-11ea-9371-cae1e1d17b16.gif)

**Comment by brumik** [comment]
Connected with #80

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-157
