### ISSUE TITLE
Line Chart Click through to Job Explorer Incorrect

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#219]
**Describe the bug**
Line chart click through to the job explorer needs to also include the `cluster_id` attribute in order to properly filter down the list of jobs.
**To Reproduce**
1. Go to 'Clusters' -> 'Line Chart'
2. Click on any data point
3. Observe the discrepancy in total job counts from chart to job explorer list

**Expected behavior**
The total job counts for line chart data points should match in the job explorer list.

**Screenshots**
![line-chart-click-through](https://user-images.githubusercontent.com/2293210/89248251-43c9aa80-d5dd-11ea-8ad8-883b6d4a14de.gif)

**Comment by appuk** [comment]
Seems like this issue is resolved, hence closing the issue
