### ISSUE TITLE
Chart builder phase 1 `clusters dashboard chart`

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#220]
# Description

Lets experiment with showing job explorer table as chart

We'd reuse existing chart we have in `clusters` page, we'd just make it configurable, so it can show us more values, small tasks
- [ ] **1. Switch job explorer table view to chart**
With a checkbox `show as chart` (@trahman73 )  ? Which would send attribute `group_by_time=True` to the API

- [ ] **2. Granularity selectbox**
By default the group_by_time returns records per day, we can control this with `granularity: daily` , so we can show it in chart as daily, monthly or yearly records 

- [ ] **3. Configure which attribute to show**
We have a list of numeric attrs available in `_options` endpoint, let user pick one. (API might need to expose what attrs are numeric and what is the Unit?)

- [ ] **4. Display mode**
If line chart and stacked bar charts are done, lets use them. (we use them for clusters dashoboard) Otherwise I'd start with line chart (we show it now, when we filter specific cluster). Then we can continue with stacked/grouped bar charts in other tasks.

- [ ] **5. Pack this as configurable component** 
So we can use this on other dashboards (cluster dashboard should use this), display more of these on 1 page, etc.

**Is your feature request related to a problem? Please describe.**
We should be able to explore the tabular data as charts in time.

**Describe the solution you'd like**
Lets do a switch to chart view, using our simplest chart in clusters dashboard

**Additional context**

We should do some experimentation in this first phase (will create separate tasks from these):

- [ ] **E1 How can we display multiple values in a chart**

This will be needed for anomaly detection correlation. We can experiment with multiselect box here. But we'll need to figure out how to display values with different units and scale.

We can allow user to pick several groups (max 3-4?) which would result in multiple y axis legends in 1 chart (see e.g. bottom of https://plotly.com/python/multiple-axes/ for inspiration)

And we should definitely allow user to render multiple charts on 1 page, so we can see multiple values correlated, with aligned x (time) axis.

**Mock up**

@trahman73 we'll need to see where to put the `show as chart` (or better naming) in the job explorer main filter. And that will also display the granularity selectbox.

Otherwise we'd use chart design as from https://tower-mockups.testing.ansible.com/analytics/dashboard/analytics/ clusters dashboard. This dashboard shows stacked bar chart and line chart when you filter specific cluster. I'd default to line chart.

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-158
