### ISSUE TITLE
Chart builder phase 2 `orgs dashboard chart`

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#221]
# Description

Lets experiment with showing job explorer table as chart

We'd reuse existing chart we have in `clusters` page, we'd just make it configurable, so it can show us more values, small tasks
- [ ] **1. Switching to grouped chart**
With a selectbox group_by we're able to group by org/cluster/template displaying as grouped bar chart we use in orgs dashboard. We must also send `group_by_time=True` to API

- [ ] **2. Configure which attribute to show**
We have a list of numeric attrs available in `_options` endpoint, let user pick one. (API might need to expose what attrs are numeric and what is the Unit?)

Also the `sort_by` will drive what orgs/templates/clusters we will show as first 5

- [ ] **3. Display mode**
We just show grouped bar chart. Does it make sense to have line/stacked bar modes?

- [ ] **4. Pack this as configurable component** 
So we can use this on other dashboards (org dashboard should use this), display more of these on 1 page, etc.

**Is your feature request related to a problem? Please describe.**
We should be able to explore the grouped data as charts in time.

**Describe the solution you'd like**
Lets show grouped data in chart

**Additional context**

We should do some experimentation in this first phase (will create separate tasks from these):

-  [ ] **E1 How can we display multiple values in a chart**

We should experiment with 3D bar charts, showing different attrs moved in Z axis.

And we should definitely allow user to render multiple charts on 1 page, so we can see multiple values correlated, with aligned x (time) axis.

- [ ] **E2 How can we paginate the chart**

We now show e.g. 1..5 org and rest. We are able to paginate this, so we can show 6..10 org and rest.

**Mock up**

@trahman73 we'll need to see where to put the `group_by` selectbox, I'll created a separate task, that this one should work also in tables. So if we don't group by time `group_by_time=False` we'll just get paginated list of templates/orgs/clusters.

Otherwise we'd use chart design as from https://tower-mockups.testing.ansible.com/analytics/orgs/analytics-orgs/ which uses grouped bar chart.

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-159
