### ISSUE TITLE
Rename clusters page 

### ISSUE THREAD

**Issue by wenottingham** [RedHatInsights/tower-analytics-frontend#222]
# Description

The "Clusters" page should be renamed to something else. "Dashboard" is one option, I am amenable to others.

Rationale: it isn't a view *of* clusters, it is a view of automation optionally sortable by clusters.

As we move towards having a general cluster view (https://github.com/RedHatInsights/tower-analytics-backend/issues/213) and we change how it constructs the graph such that it may have more options (https://github.com/RedHatInsights/tower-analytics-frontend/issues/220) it makes less sense having it named 'Clusters'.

**Additional context**
This will require updates to the Pendo guide and to the docs.

**Mock up**

Add mock up here when ready

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-160
