### ISSUE TITLE
Table builder phase 1

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#223]
# Description

Show aggregations in

- [ ] **1. Group by selectbox**
Group by `template/org/cluster` will show jobs aggregated by these, leading to paginated list of templates/orgs/clusters with job statistics.

- [ ] **2. Configure which attributes to show**
We have a list of attributes in _options, should we allow users to pick what they want to see?

- [ ] **3. Pack this as configurable component** 
E.g. the table should be render-able in more places, even as e.g. the `top 5 templates` which would be a lite mode, with a link to normal paginated table as `show all`. And we'll have some tables in job detail, etc.

**Is your feature request related to a problem? Please describe.**
We should be able to see jobs aggregated in buckets

**Describe the solution you'd like**
Lets reuse our job explorer table, to look at jobs from template/cluster/org side

**Additional context**

**Mock up**

@trahman73 we'll need design for the `group by` selectbox and we should reuse the table design of job explorer https://tower-mockups.testing.ansible.com/analytics/jobs/analytics-jobs/  (we'll need to pick the sane list of default cols to show)

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-161
