### ISSUE TITLE
Timezone discrepancy when clicking through from charts

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#227]
**Describe the bug**
The formatted time appears to be off by a day when clicking through from the charts to the job explorer.

Related #218 

**To Reproduce**
1. Go to 'Clusters'
2. Click on a single bar to view Job Explorer
3. Observe that the specified day from the chart is off by one day.

**Expected behavior**
The selected dates for the charts and the job explorer should match.

**Screenshots**
![timezone](https://user-images.githubusercontent.com/2293210/89336976-386f9100-d668-11ea-8f49-864e350e7933.gif)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benthomasson** [comment]
@kialam how does the JS library determine the timezone of the client?

**Comment by kialam** [comment]
@benthomasson currently there's no timezone implementation in the project. For now we are converting what we receive from the API to UTC.

We'd have to use something like [MomentJS Timezone](https://momentjs.com/timezone/docs/#/use-it/) which using the Internationalization API in supported browsers to[ infer the client timezone](https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/).

**Comment by benthomasson** [comment]
@ladas does the API return UTC or something else?

**Comment by Ladas** [comment]
@benthomasson yeah, everything should be in UTC

**Comment by appuk** [comment]
I verified this bug on a VM and set the timezone off by around 12 hrs.
the bug is still present, I clicked on the Cluster bar chart for Date 09/25 and the Date filter of 09/24 was applied on Job explorer page
![Screenshot from 2020-09-26 03-02-19](https://user-images.githubusercontent.com/11617351/94318512-b9575480-ff56-11ea-979a-d00cdf7af510.png)
![Screenshot from 2020-09-26 03-02-38](https://user-images.githubusercontent.com/11617351/94318517-bbb9ae80-ff56-11ea-9988-a3d9ba37a4e3.png)

**Comment by benthomasson** [comment]
@appuk @Ladas We don't rollup up data based on the end-user date. We use UTC time.  I am not sure we can fix this since that would require running rollups for every possible timezone.

**Comment by Ladas** [comment]
@benthomasson yeah, we can only do UTC now, so UI should follow that. If it would be customer a request, we could do rollups in more timezones (limited number of picked timezones). Or switching our backend DB technology, there could be more options

**Comment by benthomasson** [comment]
@kialam let's not implement local time translation at this point.   We can remove the `utc()` call for now.

**Comment by kialam** [comment]
@appuk I think this is ready to be re-tested - hopefully this fixes the date off by one bug we're seeing 🤞 .

**Comment by appuk** [comment]
I see it is still not fixed :(

![timezone](https://user-images.githubusercontent.com/11617351/94823599-08c3d780-03d2-11eb-9ac2-cca83071b295.gif)

**Comment by appuk** [comment]
🎉 
![tz](https://user-images.githubusercontent.com/11617351/95219053-92c8d180-0812-11eb-9b91-df9e03efe682.gif)

**Comment by benthomasson** [comment]
There are still timezone issues with the UI.  It appears that the dates are being converted the wrong way and are 8 hours off.  Since everything is UTC we should not be doing any conversions.

**Comment by appuk** [comment]
Verified this on prod-beta, and now I see the right time in all the charts/ template timestamps. hence closing.
