### ISSUE TITLE
Present dates in local time

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#229]
# Description

Dates in the UI should be presented to the user in their local timezone. Currently it is formatted as UTC

**Is your feature request related to a problem? Please describe.**
Related #228 and #227 

**Describe the solution you'd like**
The UI should be responsible for two things:
1. Date params should be formatted as UTC when sent to the API.
2. Dates returned from the API should be presented in the users local timezone.

**Comment by kialam** [comment]
Implement using Internationalization API. List of supported browsers [here](https://caniuse.com/#feat=internationalization).

**Comment by jctanner** [comment]
https://stackoverflow.com/a/34602679

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-164
