### ISSUE TITLE
Job Explorer v1 Sort by options need to match default attributes

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#232]
**Describe the bug**
Currently the list of `sort_by` options is the default set returned by the v1 job explorer API. It should match the attributes we specify when we make a request to the v1 job explorer API. 

**To Reproduce**
1. Go to 'Job Explorer'
2. Click on 'Sort by' dropdown
3. Observe the list of options available

**Expected behavior**
It should match the default attributes we pass to the v1 job explorer API. It does not make sense to have the user be able to sort by attributes we are not showing in the UI. The default list of job explorer attributes is found in [constants.js](https://github.com/RedHatInsights/tower-analytics-frontend/blob/jo_job-explorer-list-view/src/Utilities/constants.js#L2-L13).

**Screenshots**
![Screen Shot 2020-08-05 at 11 10 45 AM](https://user-images.githubusercontent.com/2293210/89430064-57bffa00-d70c-11ea-9a68-0959091f0204.png)

**Comment by appuk** [comment]
![image](https://user-images.githubusercontent.com/11617351/91084015-52721300-e619-11ea-9b32-5bda20617a7e.png)
The sort by options now only shows the attributes that are already visible in UI, hence closing
