### ISSUE TITLE
Link out to Job Explorer from Top Templates Detail Modal does not pass cluster_id

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#233]
**Describe the bug**
When filtering by a specific cluster in the Clusters view, when a user clicks on the View all jobs link from a specific template detail modal, the job explorer list should also be filtered by that cluster.

**To Reproduce**
1. Go to 'Clusters'
2. Click on a specific cluster
3. Click on a template in the Top Templates area
4. Click on View All Jobs link
5. Observe that the Job Explorer List is not filtered by specific cluster.

**Expected behavior**
The linkout should include the selected cluster as part of the pre-filtered view in the job explorer list.

**Screenshots**
![linkout_missing_cluster_id](https://user-images.githubusercontent.com/2293210/89432981-c0f53c80-d70f-11ea-909e-375fe3010174.gif)

**Comment by appuk** [comment]
The link now also applies the cluster filter, hence closing this issue, 

![cluster-filter](https://user-images.githubusercontent.com/11617351/92262232-ced1e500-eea8-11ea-851d-530ffc1786d1.gif)

will comment on the main issue if I find any other issues with filtering
