### ISSUE TITLE
Job Explorer UI Cleanup Tasks

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#238]
# Description
Here are the individual tasks remaining for cleaning up the Job Explorer UI:
1. Refactor filter toolbar with the following changes:
- Break out Sort By into it's own dropdown
- Break out Date Range selector into it's own drop down
- Move "Ignore nested workflows..." toggle into filters dropdown
- Remove any default filters/chips when a user first visits the Job Explorer page.
Edit @brumik ^^ should be done as part of your filter toolbar component refactor for ease of reuse.

Current implementation:
<img width="1300" alt="Screen Shot 2020-08-11 at 8 46 34 PM" src="https://user-images.githubusercontent.com/2293210/89962788-c96bdc80-dc13-11ea-9506-b97e2f86af50.png">

Mockup:
<img width="858" alt="Screen Shot 2020-08-11 at 8 42 16 PM" src="https://user-images.githubusercontent.com/2293210/89962595-32068980-dc13-11ea-8419-d36db10555fe.png">

2. Update Pagination [PR OPEN]:
- Top of Job Explorer page should have the minimized pagination component.
- Bottom of Job Explorer page should have the default pagination component.
- Remove "Total Count" section at the top header.

Mockup:
<img width="1531" alt="new_pag" src="https://user-images.githubusercontent.com/2293210/89962897-0c2db480-dc14-11ea-8f84-90fbb199f072.png">

3. Update page header title from "Automation Analytics | All jobs" to "Jobs explorer" [PR OPEN].

4. Use compact version of datalist component [PR OPEN].

Current implementation:
<img width="859" alt="Screen Shot 2020-08-11 at 8 51 06 PM" src="https://user-images.githubusercontent.com/2293210/89963011-6d558800-dc14-11ea-91d3-33892b146e13.png">

Mockups:
<img width="682" alt="Screen Shot 2020-08-11 at 8 51 14 PM" src="https://user-images.githubusercontent.com/2293210/89963019-721a3c00-dc14-11ea-8cbf-edc4863f0e95.png">

5. Handle long drop downs -> set max height for the dropdown selector element with scrollbar [PR OPEN].

# Verification
Mockups here:
https://tower-mockups.testing.ansible.com/analytics/jobs/analytics-jobs/

**Comment by appuk** [comment]
@jeanetteobr I see that the data in columns start a bit earlier than the column header

![Screen Shot 2020-10-05 at 3 57 16 PM](https://user-images.githubusercontent.com/11617351/95125789-7732cd80-0723-11eb-8d33-e978a5764ca2.png)

can you fix the alignment of the columns?

**Comment by jeanetteobr** [comment]
@appuk Thanks for pointing that out.

**Comment by brumik** [comment]
@kialam @jeanetteobr This is done right? I marked it as done (since @jeanetteobr already marked it Done once, I guess there is nothing more to add?). If I am mistaken mark it appropriatly.

**Comment by kialam** [comment]
@brumik yes I believe this is done.
