### ISSUE TITLE
Add currency drop down to ROI calculator

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#246]
# Description

Add a drop down selector for the currency to the ROI calculator.  This changes the currency unit everywhere on the page.  It does not change the calculations at all.

For the first implementation this does not need to be detected or persisted.  Only change the currency unit on the UI page on the client.

**Comment by brumik** [comment]
Is there any mockup for this? I can pass a currency selector in the new toolbar in #323

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-167
