### ISSUE TITLE
Disable linking to the job explorer from the others category on Organization Status view

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#249]
**Describe the bug**

![Screen Shot 2020-08-24 at 3 21 55 PM](https://user-images.githubusercontent.com/44381/91087034-cf9f8700-e61d-11ea-8454-2893aac68a50.png)

Disable linking to the job explorer from the others category on Organization Status view.

**To Reproduce**
1. Go to Organization Status
2. Click on the others bar
3. nothing happens

**Expected behavior**

The others bars are not clickable.

**Screenshots**

**Comment by appuk** [comment]
@benthomasson is this a duplicate of https://github.com/RedHatInsights/tower-analytics-frontend/issues/193 ?

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-168
