### ISSUE TITLE
automation calculator roi filters

### ISSUE THREAD

**Issue by IPvSean** [RedHatInsights/tower-analytics-frontend#252]
# Description

*Note: Update this description throughout the life of the issue* 

**Is your feature request related to a problem? Please describe.**

we are marketing automation analytics use cases to help with chargebacks as an option, however there needs to be some additional filters to allow chargebacks easier.  Chargebacks allow the automation organization (whoever is running the platform clusters) to charge and measure monetarily how much they are saving, or will charge other groups/organizations at their company.

**Describe the solution you'd like**

The following allows you to do a chargeback to individual teams:
- filter by organization within the automation calculator
- filter by cluster within the automation calculator

The following allows you to zoom into a timeline to match billing procedure for a specific companies policy
- filter by arbitrary date (e.g. June1 through June15, FY15, FY16, August 1st through October 1st)

**Describe alternatives you've considered**
no way to do this currently

**Additional context**
this came out of the ansible weekly office hours from the fields (SSP, AEs, SAs and consultants).

**Mock up**

Add mock up here when ready

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by Ladas** [comment]
is this a duplicated of https://github.com/RedHatInsights/tower-analytics-frontend/issues/199 ? 

Or we want a separate issue for applying the 'job explorer' filter to all dashboards?

**Comment by brumik** [comment]
Only the org and the cluster filters needed on top of the date filter in the Automation Calculator page?

@Ladas @IPvSean

**Comment by Ladas** [comment]
@brumik you should base it on what filters are available in _options endpoint. So when we move to @AparnaKarve 's ROI _options, it will show the right ones (we will remove some and probably add some later, like filter by inventory)

**Comment by brumik** [comment]
Then I think this issue is kinda duplicate

**Comment by brumik** [comment]
Duplicate
