### ISSUE TITLE
Catch json parsing errors and rethrow them with the full response

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#253]
# Description

Sentry gives unhelpful error messages like this:  

> SyntaxError: Unexpected token I in JSON at position 0

I'd rather see the entire error message from the server in the sentry report.   So we should catch all json parsing errors and rethrow them with the full response from the server so we can see it in sentry.

# Verification

< remove if not needed >

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-169
