### ISSUE TITLE
After 2x refresh bookmarking is failing on the Job Explorer page

### ISSUE THREAD

**Issue by brumik** [RedHatInsights/tower-analytics-frontend#255]
**Describe the bug**
Job explorer filters reset after 2 page-hard-refresh.

**To Reproduce**
1. Go to Job Expoler
2. Set a custom filter
3. Do 2x page refresh (F5 on chrome)
4. See the filter reset to default

**Expected behavior**
Filter stays the same.

**Screenshots**
![Screencast from 09-02-2020 03_25_38 PM](https://user-images.githubusercontent.com/8531681/91989402-c35bae00-ed30-11ea-9ce6-7e05dfb0111a.gif)

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Browser chrome

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-170
