### ISSUE TITLE
[RFE] Enable clicking on Others category

### ISSUE THREAD

**Issue by appuk** [RedHatInsights/tower-analytics-frontend#259]
# Description

Follow up to: https://github.com/RedHatInsights/tower-analytics-frontend/issues/193
This is a placeholder for figuring out how to pass the list of organizations, after figuring that out, we can enable clicking on the others tab on the "Organization statistics" page

**Describe the solution you'd like**
One solution recomended by @Ladas is add support to API for exclusion
example: Add a `not_in` operator and we'd pass org_id_operator: 'not_in' and org_id: [ids we're currently showing]

**Mock up**

Add mock up here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by Ladas** [comment]
@trahman73 @kialam we'd need a mockup of how this would look like with operator

right now we have:
    Organization: [org_1, org_2, org3]

And we'd allow operator so e.g:
    Organization: [are/in] [org_1, org_2, org3]

And if I want everything except these orgs I'd do:
    Organization: [are not/not in] [org_1, org_2, org3]

I think tower supports filtering with operators?

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-171
