### ISSUE TITLE
"View all jobs" link should only apply the filter of Successful and Failed jobs

### ISSUE THREAD

**Issue by appuk** [RedHatInsights/tower-analytics-frontend#260]
**Describe the bug**
Main Feature: https://github.com/RedHatInsights/tower-analytics-frontend/issues/183

On click of "View all jobs" link in templates modal, all the statuses are applied as filter, when it should ideally only show the jobs that are visible in the Chart i.e Successful and Failed jobs
![image](https://user-images.githubusercontent.com/11617351/92789943-515f1680-f379-11ea-936a-07aa40be40f3.png)

**To Reproduce**
1. Go to 'Clusters' page
2. Click on one of the templates in "Top Templates" section
3. Click on "View all jobs"
4. See the status filter applied

**Actual behavior**
All job status are applied as filter

**Expected behavior**
Only apply filter for Successful and Failed jobs

**Comment by appuk** [comment]
cc @kialam @jeanetteobr @brumik

**Comment by brumik** [comment]
The status filters are applied to match the "Number of runs" in the template modal.

Modal:
![Screenshot from 2020-09-11 11-11-27](https://user-images.githubusercontent.com/8531681/92900152-b9683800-f41f-11ea-8898-293ee17cebcb.png)

Job Exproler
![Screenshot from 2020-09-11 11-12-17](https://user-images.githubusercontent.com/8531681/92900156-ba00ce80-f41f-11ea-9763-6c3649c6a62f.png)

**Comment by appuk** [comment]
Ahh makes sense, if that's the case, then isn't it better to just not apply Job Status filter instead of applying the filter for all the statuses? Because both of them will yield the same results and selecting all job status might make the filter chips look bulky?

**Comment by brumik** [comment]
Passing empty array makes the job explorer page to apply the default status filters... yet. Ill look into it

**Comment by appuk** [comment]
Ok thank you for looking into this!

**Comment by brumik** [comment]
@kialam I was playing with this a few hours but it seems like
1. We cannot encode an empty array
2. We cannot parse an empty array
3. The API returns correct data (any state) if we pass an empty array to the status or we don't pass the status at all.

I was trying to get the bookmarking accept empty array -> make the difference between `not passing` or `passing an empty array` but at this point starts to feel like refactoring the whole component.

**Comment by appuk** [comment]
Closing this as "will not do" after discussing offline
