### ISSUE TITLE
Job Explorer view - Rows with long cluster name are misaligned

### ISSUE THREAD

**Issue by appuk** [RedHatInsights/tower-analytics-frontend#263]
**Describe the bug**
In Job explorer view, all the columns are misaligned for a row with long cluster name

In the screenshot below, the alignment in 1st row looks correct. While in 2nd row, the status icon as well as the Job type had to move to the outer side to make space for the long cluster name

![image](https://user-images.githubusercontent.com/11617351/92801733-dea76880-f383-11ea-9afe-5d4372b5f0f5.png)

that might be happening because there is no wrapping in place for Cluster name

**To Reproduce**
1. Go to 'Job Explorer' page
2. Observe a row with long cluster name

**Expected behavior**
the long cluster name should be wrapped properly so that it does not mess with the data around it

**Comment by jeanetteobr** [comment]
@appuk I can't not able to replicate this bug on my end. Please see the attached .gif below:

![](http://g.recordit.co/srtgkvVtUN.gif)

I edited the Cluster name in the first row and added an Org name via the DOM tree. It doesn't look like the Org column is offest by the long cluster name. I'm wondering if the API needs to return a long Cluster name in order for the bug to trigger?

**Comment by appuk** [comment]
Possibly? can you check by passing the Cluster name through API?

**Comment by appuk** [comment]
the wrapping is now in place:
![Screen Shot 2020-10-05 at 3 55 20 PM](https://user-images.githubusercontent.com/11617351/95125627-3b980380-0723-11eb-8aaa-ad290873f6f1.png)
