### ISSUE TITLE
UXD Audit: Update Chart Tooltips

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#273]
# Description
Update tooltip icons to PF4 standard

# Verification
Before:
![Screen Shot 2020-09-23 at 11 14 41 AM](https://user-images.githubusercontent.com/2293210/94032539-089e5900-fd8e-11ea-8bcf-ba29dcd53934.png)

After:
![Screen Shot 2020-09-23 at 11 14 54 AM](https://user-images.githubusercontent.com/2293210/94032576-0e943a00-fd8e-11ea-82cd-afb542e0bffb.png)

**Comment by appuk** [comment]
Looks good! 
![Screen Shot 2020-12-01 at 1 05 37 PM](https://user-images.githubusercontent.com/11617351/100779240-17306e80-33d6-11eb-9462-661c6638f157.png)
