### ISSUE TITLE
UXD Audit: Remove top bounding box from charts

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#274]
# Description
Remove bounding box from Organization Statistics and Automation Calculator charts. They should be #4F5255 hex value.

# Verification
Before: 
![Screen Shot 2020-09-23 at 11 19 22 AM](https://user-images.githubusercontent.com/2293210/94033213-bad62080-fd8e-11ea-9d85-a282155b4b6a.png)
![Screen Shot 2020-09-23 at 11 19 12 AM](https://user-images.githubusercontent.com/2293210/94033214-bad62080-fd8e-11ea-981d-52ea4ac05294.png)

After:
![Screen Shot 2020-09-23 at 11 19 48 AM](https://user-images.githubusercontent.com/2293210/94033207-b9a4f380-fd8e-11ea-929a-542e2ea3f255.png)
![Screen Shot 2020-09-23 at 11 19 39 AM](https://user-images.githubusercontent.com/2293210/94033211-ba3d8a00-fd8e-11ea-9620-2b08841bd9ee.png)

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-173
