### ISSUE TITLE
UXD Audit: Move filters to title section

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#276]
# Description
Currently top level filters live in their own section/header. The recommendation from the UXD team is to move the filters into the page title section.

I think this warrants more discussion before we attempt to implement. For example, this is how it would this look with numerous filters selected:
![Screen Shot 2020-09-23 at 11 41 10 AM](https://user-images.githubusercontent.com/2293210/94035948-c0813580-fd91-11ea-86f2-262b9867bbf8.png)

compared to cleared filters/no filters:
![Screen Shot 2020-09-23 at 11 43 06 AM](https://user-images.githubusercontent.com/2293210/94036147-ffaf8680-fd91-11ea-9fe6-3ea4df0ec16e.png)

Are we okay with the inconsistent amount of white space the title header could have based on user selection?

**Comment by jeanetteobr** [comment]
@kialam @trahman73 @benthomasson Happy to implement this so it can get into the 1.2 release. However, if more discussion is needed perhaps we should think about attaching this ticket to another release.

**Comment by trahman73** [comment]
@jeanetteobr I believe @kialam and I discussed this further offline and wanted to proceed with the issue as is. Top level filters would be moved to the top header area in the Dashboard, Org Stats, and ROI areas. Any filter that is part of a table would remain as is.

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-174
