### ISSUE TITLE
UXD Audit: Top Templates Detail Modal enhancements

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#278]
# Description

1. Change “Last 5 jobs” label to table header
2. Move “View all jobs” link to footer
3. Add “Type” to summary
4. Add status column next to Id/Name
5. Let Id/Name and Cluster wrap and not truncate
6. Change close button to blue filled primary button 

# Verification
Before:
![Screen Shot 2020-09-23 at 11 59 40 AM](https://user-images.githubusercontent.com/2293210/94038340-4e5e2000-fd94-11ea-879f-2a0328000a87.png)

After:
![Screen Shot 2020-09-23 at 11 56 15 AM](https://user-images.githubusercontent.com/2293210/94038246-35556f00-fd94-11ea-9ee8-3e5d94e11d58.png)

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-176
