### ISSUE TITLE
UXD Audit: Job Explorer add host status and top failed tasks barchart to expanded details

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#281]
# Description
Add “Host status” and “Top failed tasks” status bars to table row dropdown
# Verification
![Screen Shot 2020-09-23 at 12 20 21 PM](https://user-images.githubusercontent.com/2293210/94040628-2d4afe80-fd97-11ea-9bdb-226249890962.png)

@Ladas do we have what we need to create this barchart from the v1 API?

**Comment by Ladas** [comment]
yes as part of https://github.com/RedHatInsights/tower-analytics-backend/pull/485

backend issue https://github.com/RedHatInsights/tower-analytics-backend/issues/469

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-178
