### ISSUE TITLE
UXD Audit: Chart Legend make numbers bigger for better legibility

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#283]
# Verification
Before:
![Screen Shot 2020-09-23 at 12 30 38 PM](https://user-images.githubusercontent.com/2293210/94041748-a8f97b00-fd98-11ea-9a35-8788f870b4ab.png)

After:
![Screen Shot 2020-09-23 at 12 30 49 PM](https://user-images.githubusercontent.com/2293210/94041755-ac8d0200-fd98-11ea-833a-110af8a88054.png)

**Comment by appuk** [comment]
@jeanetteobr the numbers represented should either be a count, or a percentage like you showed in the screenshot above
although looks like it currently just displays the count as percentage

![Screen Shot 2020-12-01 at 12 57 20 PM](https://user-images.githubusercontent.com/11617351/100778855-8bb6dd80-33d5-11eb-84a2-daaa681f1a3d.png)

```
count: 75
failed_count: 52
id: 41
name: "Default"
success_rate: 23
successful_count: 17
```

can you please make the change in logic? thanks!

**Comment by jeanetteobr** [comment]
@appuk I've got a PR open for this issue: https://github.com/RedHatInsights/tower-analytics-frontend/pull/371

**Comment by appuk** [comment]
I don't see the % sign anymore. good to close now
