### ISSUE TITLE
UXD Audit: Chart labels: fix spacing of axis labels

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#284]
# Description
When resizing or depending on the number of templates show, the spacing between the template names and the bar can get crowded. Suggestion: fix spacing between template name and bar on the chart in the Automation Calculator page.

# Verification
<img width="48" alt="Screen Shot 2020-09-23 at 12 42 33 PM" src="https://user-images.githubusercontent.com/2293210/94044059-a64c5500-fd9b-11ea-89f4-3f40279dfcf5.png">
<img width="80" alt="Screen Shot 2020-09-23 at 12 42 20 PM" src="https://user-images.githubusercontent.com/2293210/94044068-a8aeaf00-fd9b-11ea-82d7-2607494a1ac0.png">

**Comment by appuk** [comment]
![Screen Shot 2020-12-01 at 1 10 31 PM](https://user-images.githubusercontent.com/11617351/100779651-b0f81b80-33d6-11eb-8aca-6441cc5760e7.png)
Looks much better now!
