### ISSUE TITLE
UXD: Use popover instead of tooltip for Automation Calculator page

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#285]
# Description
Use PF's [Popover](https://www.patternfly.org/v4/documentation/react/components/popover) component instead of the Tooltip component n the Automation Calculator page.
# Verification
Before:
![Screen Shot 2020-09-23 at 12 56 01 PM](https://user-images.githubusercontent.com/2293210/94044464-2c689b80-fd9c-11ea-80d8-bdd7f527ab81.png)

After:
![Screen Shot 2020-09-23 at 12 55 49 PM](https://user-images.githubusercontent.com/2293210/94044477-3094b900-fd9c-11ea-9e4e-3ab87676ac86.png)

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-179
