### ISSUE TITLE
UXD Audit: Automation Calculator page suggestions

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#286]
# Description

1. Combine editable cards on the right into a panel
2. Remove template toggles under “Calculate your automation” as the new master filter will replace this function
3. Make “total savings” number bigger for improved hierarchy 

# Verification
![Screen Shot 2020-09-23 at 12 58 08 PM](https://user-images.githubusercontent.com/2293210/94044678-76ea1800-fd9c-11ea-9c5b-f35d8fc36726.png)

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-180
