### ISSUE TITLE
The user should be able to hover on the data point even if the graph bar is too small to even be visible

### ISSUE THREAD

**Issue by appuk** [RedHatInsights/tower-analytics-frontend#287]
# Description
When the delta between 2 data points on a graph is large, (for example, one bar represents 12k jobs, while another bar represent 20 jobs), the bar with smaller data is not visible, in such scenarios, it is frustrating trying to hover over the datapoint (and also click on it)

This scenario is very common in prod as well, as big chunks of jobs are run in maintenance windows.

Hence it would be great to find a way that the user can always hover over the smaller data points

**Describe the solution you'd like**
As mentioned by @Ladas, the hover can be shown at a point near the vertical line, which will also enable seeing data points with 0 value

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by appuk** [comment]
One more scenario where larger delta is affected:
![Screen Shot 2020-09-23 at 3 05 54 PM](https://user-images.githubusercontent.com/11617351/94057918-4e6b1980-fdae-11ea-9761-0215495049b4.png)
The hover shows 0% where the actual value is around 0.0042%

not sure if we want to address this issue as part of this ticket

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-181
