### ISSUE TITLE
Generate security manifest

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#292]
# Description

Use these scripts to generate a security manifest for this project:

https://github.com/ansible/ansible-hub-ui/blob/master/.travis/update_manifest.sh
https://github.com/ansible/ansible-hub-ui/blob/master/.travis/generate_manifest.js

To produce a file like this:

https://raw.githubusercontent.com/RedHatInsights/manifests/stable/automation-hub/automation-hub-ui.txt

**Comment by kialam** [comment]
@benthomasson can this be closed?

**Comment by jctanner** [comment]
@benthomasson  bump
