### ISSUE TITLE
Success rate of Top Templates displayed as unavailable

### ISSUE THREAD

**Issue by appuk** [RedHatInsights/tower-analytics-frontend#294]
Feature: https://github.com/RedHatInsights/tower-analytics-backend/issues/73

**Describe the bug**
If a Job Templates in Top Templates has all Failed jobs (i.e Success rate is 0%), it displays the Success rate as `unavailable`

<img width="1330" alt="Screen Shot 2020-09-25 at 2 53 28 PM" src="https://user-images.githubusercontent.com/11617351/94305280-ed268000-ff3e-11ea-8297-3a68dd2544c0.png">

**To Reproduce**
1. Go to Clusters page
2. Click on a Job Template in Top Templates section that has all Failed jobs
3. Observe that Success rate is `unavailable`

**Expected behavior**
Success rate should be `0%`

**Comment by jctanner** [comment]
I can reproduce this bug with the test data created by `make init` if I choose teh ec2-52-90-106-58 cluster and then select template_name_2

**Comment by jctanner** [comment]
reopening for testing

**Comment by appuk** [comment]
Looks good! 👍 
![Screen Shot 2020-09-29 at 3 07 58 PM](https://user-images.githubusercontent.com/11617351/94604462-bcf41f80-0265-11eb-9345-a25793834fc6.png)
