### ISSUE TITLE
Add a message if most failed task is null

### ISSUE THREAD

**Issue by appuk** [RedHatInsights/tower-analytics-frontend#295]
Feature: https://github.com/RedHatInsights/tower-analytics-backend/issues/73

**Describe the bug**
If a Job fails before it reaches any task or before actually running the tasks on a host, the most failed task is `Null`.
We can add an enhancement where in such cases the Most failed case should be displayed as: `Failed before reaching any task`

**To Reproduce**
1. Go to Clusters page
2. Click on JT (that failed before reaching any task) on Top Templates module
3. Observe that Most failed task is `null`

**Comment by appuk** [comment]
cc @Ladas

**Comment by appuk** [comment]
cc @kialam @trahman73 Please feel free to move this to 1.2 if you think this might not make it in 1.1

**Comment by Ladas** [comment]
so there are probably 2 things:

1. When API returns `most_failed_tasks: []`. We show `Most failed tasks: Unavailable`, the section should probably just disappear as @benthomasson mentioned in the slack chat (there is no failure). I think we plan to do this with 1.2 design (most failed tasks bars)

2. When API can't determine the task name, it returns `null`, e.g. from v0_1 API:
```
most_failed_tasks: [{fail_rate: 83, task_name: null, failed_count: 5, failed_hosts_count: 0},…]
0: {fail_rate: 83, task_name: null, failed_count: 5, failed_hosts_count: 0}
    fail_rate: 83
    failed_count: 5
    failed_hosts_count: 0
    task_name: null
1: {fail_rate: 17, task_name: "Add yum repository", failed_count: 1, failed_hosts_count: 1}
    fail_rate: 17
    failed_count: 1
    failed_hosts_count: 1
    task_name: "Add yum repository"
```

this is v0_1, in v1 we also return `module_name`, so then there are 2 results from this:

R1. task_name is null but it has module name => users didn't add any task name, we can show module name
R2. both task_name and module name are null => the job failed before reaching any task (e.g. failing to fetch role/collection ) or there is no failed task (not sure how it could happen)

----------

@kialam @trahman73 @appuk  

I'd say lets do these edge cases as part of https://github.com/RedHatInsights/tower-analytics-frontend/issues/278 , so moving it to 1.2. (if it'll make sense, API can return some of these)

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-182
