### ISSUE TITLE
Job Explorer is named differently in sidebar vs title

### ISSUE THREAD

**Issue by wenottingham** [RedHatInsights/tower-analytics-frontend#317]
**Describe the bug**

Job explorer is named differently on the sidebar and in the title.

![Screenshot from 2020-10-12 10-10-35](https://user-images.githubusercontent.com/5208768/95773644-ddbc6c00-0c8c-11eb-8637-a1c5f6a5b95f.png)

**Comment by appuk** [comment]
![Screen Shot 2020-11-05 at 10 28 31 AM](https://user-images.githubusercontent.com/11617351/98260760-aff7d980-1f51-11eb-89c7-302c02ee1e42.png)
The titles match now
