### ISSUE TITLE
Help question mark UX feedback

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#318]
**Describe the bug**

Feedback on Jobs Explorer from Cloud Platform UX team...

> I’m clicking on the question circle icon and nothing is coming up
> question icons should be an unfilled question circle icon, and it should be grey by default, and black on hover/click

**To Reproduce**
1. Go to job explorer
2. Click on the help question circle icon
3. Nothing happens (question circle does show help on hover)

**Expected behavior**

Clicking on question circle should show help too.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-183
