### ISSUE TITLE
User level stats

### ISSUE THREAD

**Issue by nleiva** [RedHatInsights/tower-analytics-frontend#319]
# Description

Could we display "Top users" of an organization in Automation Analytics for different categories?

- Total runtime of Job Templates run by a user.
- Total runtime of Job Templates a user has authored.
- Etc.

This is just an idea that came up in a Slack discussion. Feel free to ignore it.

**Comment by kialam** [comment]
@benthomasson or @kyleabenson would one of you like to chime in on this?

**Comment by benthomasson** [comment]
We do not collect user level information at this time.   We are trying not to collect personally identifying information.
