### ISSUE TITLE
if the backend does not support job explorer, clicking on it in the frontend breaks the entire app.

### ISSUE THREAD

**Issue by jctanner** [RedHatInsights/tower-analytics-frontend#320]
**Describe the bug**
Getting a 404 for the job explorer backend is fatal to the frontend. No pages will load again until hard refreshed.

**To Reproduce**
1. spin up a backend with no job explorer support
2. click on job explorer
3. accept the note about the new feature
4. observe the lempty light gray div
5. click on any other items in the nav such as clusters or roicalc
6. the empty gray div does not go away

**Expected behavior**
We need cleaner handling of 404s so that it doesn't break the whole app.

**Comment by kialam** [comment]
@jctanner would we see this on production given that the API and UI for job explorer are now released?

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-184
