### ISSUE TITLE
Update asynch component Loading screen

### ISSUE THREAD

**Issue by brumik** [RedHatInsights/tower-analytics-frontend#325]
# Description
While waiting for the components to load a simple non-styled div with 'Loading...' is displayed. I think it should be updated to match the UX design

![Screenshot from 2020-10-27 10-01-13](https://user-images.githubusercontent.com/8531681/97279597-79c4a680-183b-11eb-9599-d427476c9b0f.png)

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-185
