### ISSUE TITLE
Refactor: snake_case from API to camelCase

### ISSUE THREAD

**Issue by brumik** [RedHatInsights/tower-analytics-frontend#327]
# Description
We are using snake_case for variables that are coming from the API. Optimally we would convert the keys of these objects to camelCase before any processing: in the Api.js file.

After #323 gets merged there will be a function: `keysToCamel` in the `Utilities/helpers.js`. Then we could use this function in the `Api.js` like this:

```js
function handleResponse(response) {
    return response.json().then(json => {
        if (response.ok) {
            // return json; -- replace this line
            return keysToCamel(json); // with this line
        }
        ...
}
```

it would ensure that all data (not errors tough). Then we need to change all data from the API from snake_case to camelCase all across the App.

**Note**: It needs also refactoring all the snake_cased keys the App is currently using from the API to camelCase

**Comment by kialam** [comment]
I am starting to think that this needs more discussion as there will still be lines of code that use snake case (render methods for lists). I suppose you could destructure and then rename to camel case. Not sure if this level of indirection provides us any real benefit.

**Comment by brumik** [comment]
@kialam Which render methods for list use snake_case? I have just seen use cases of snake_case where the data came from the API.

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-186
