### ISSUE TITLE
Legend in charts has wrong size and the has the % symbol where it is not a % for sure

### ISSUE THREAD

**Issue by brumik** [RedHatInsights/tower-analytics-frontend#333]
The legend now has % --> this is misleading and most probably wrong see:

![Screenshot from 2020-11-02 14-20-11](https://user-images.githubusercontent.com/8531681/97872699-c36b3080-1d16-11eb-9a71-8b620c3665c8.png)

Also, the legend font sizes are different for the label and the value: 12px for the title 15 for the text. I believe this was introduced in UXD audit changes: https://github.com/RedHatInsights/tower-analytics-frontend/commit/192ed854ca893dd7d201406ea0cd61875505b244

@jeanetteobr

**Comment by benthomasson** [comment]
@jeanetteobr Did the % come from the UXD feedback?  I would prefer to keep the raw counts instead of percentages on the legend.

**Comment by Ladas** [comment]
yeah just noticed this, this needs to be recomputed if we are showing % (afaik the UXD feedback was showing both percentage and absolute number?)

**Comment by Ladas** [comment]
@kialam @jeanetteobr  hm, my comment about showing also the absolute number is gone now https://docs.google.com/presentation/d/1FTNmLVUwbXWX1NxcN31yvtzYBrVDlRNioQN1Cehfx7k/edit#slide=id.g9376ae2f39_0_46

I believe we were talking about that and it was similar to what Cost team is doing (also formulation of the others)

**Comment by Ladas** [comment]
I believe we were talking about something like this  (just pie chart)

![Screenshot from 2020-11-04 14-26-43](https://user-images.githubusercontent.com/1737058/98117368-ee39be00-1ea9-11eb-8a12-b36554abfc8b.png)

Without the absolute numbers, the percentages are kind of without meaning
----
screenshot from cost mgmt demo https://drive.google.com/file/d/1R8Hm_cRYYhxjObVNK2_rub8TY-BGUtSu/view

**Comment by Ladas** [comment]
@kialam I think we agreed that the `X others` name would be added in the API? If that is the case I'll create a backend issue for it :-)

**Comment by jeanetteobr** [comment]
@benthomasson The percentages were part of the UXD Audit. I admit that I may have misinterpreted what the issue related to the change was asking for. I'll have a PR up that fixes this sometime today.

**Comment by jeanetteobr** [comment]
Here's the PR that addresses this issue: https://github.com/RedHatInsights/tower-analytics-frontend/pull/371
