### ISSUE TITLE
Add Filter Toolbar to Notifications Page

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#337]
Mockup:
![Screen Shot 2020-11-03 at 11 50 37 AM](https://user-images.githubusercontent.com/2293210/98015576-f0791b00-1dca-11eb-8439-9aeb4c3fb3a8.png)

Depends on https://github.com/RedHatInsights/tower-analytics-frontend/pull/321

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-189
