### ISSUE TITLE
Interactive legend for all charts

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#344]
# Description

All the charts (timeseries, pie, etc.) should have interactive legend https://www.patternfly.org/2020.08/documentation/react/charts/chartlegend/interactive-legend , since that is standard in analytics apps

**Comment by Ladas** [comment]
cc @kialam  @trahman73 @brumik

**Comment by jeanetteobr** [comment]
@Ladas @kialam @trahman73 @brumik this enhancement didn't come out of the UXD Audit AA underwent a few weeks ago. I'm putting a low priority label on this for now. We don't have any PF models currently that would demonstrate how our filters should work with an interactive legend. This is worth having a larger discussion.

**Comment by Ladas** [comment]
@jeanetteobr btw. filters and interactive legend are unrelated. The interactive legend just show/hide the series tied to individual legend (so pure javascript implementation like in the example ^)

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-190
