### ISSUE TITLE
Filterable Toolbar Not Responsive

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#345]
**Describe the bug**
The filterable toolbar is not responsive.

**To Reproduce**
1. Go to Job Explorer page.
2. Observe that the toolbar has overflow on the right hand side.

**Expected behavior**
The toolbar should be responsive.

**Screenshots**
![Screen Shot 2020-11-09 at 12 02 35 PM](https://user-images.githubusercontent.com/2293210/98572913-2d8a5500-2284-11eb-805a-abd3a410f137.png)

**Comment by appuk** [comment]
![Screen Shot 2020-12-01 at 1 21 34 PM](https://user-images.githubusercontent.com/11617351/100780777-26b0b700-33d8-11eb-9524-9ae060aa02f9.png)

👍

**Comment by appuk** [comment]
opps sorry, wrong place to close the issue :)

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-191
