### ISSUE TITLE
Filterable Toolbar Settings Close Button Does Not Work

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#346]
**Describe the bug**
The X button in the expanded settings section of the filterable toolbar does not close/hide the settings section.

**To Reproduce**
1. Go to 'Job Explorer'
2. Click on Settings
3. Click on X button
4. Observe that the settings menu stays open.

**Expected behavior**
The X button should hide the settings menu in the filterable toolbar.

**Screenshots**
![no-close](https://user-images.githubusercontent.com/2293210/98573181-8eb22880-2284-11eb-9870-40e7fadd5a98.gif)

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-193
