### ISSUE TITLE
Filterable Toolbar Compact Pagination Dropdown Items Hidden

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#347]
**Describe the bug**
The compact pagination per page selection items become hidden when expanded.

**To Reproduce**
1. Go to 'Job Explorer'
2. Click on 'per page' dropdown by compact pagination component.
3. Observe that 5 per page is hidden and not selectable

**Expected behavior**
All dropdown items should be visible and selectable.

**Screenshots**
![Screen Shot 2020-11-09 at 12 18 10 PM](https://user-images.githubusercontent.com/2293210/98574443-edc46d00-2285-11eb-9474-b51f4b662b3a.png)

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-194
