### ISSUE TITLE
Line chart overlaps are hard to distinguish

### ISSUE THREAD

**Issue by wenottingham** [RedHatInsights/tower-analytics-frontend#348]
**Describe the bug**
This is degenerate data, but:

Cluster data with an equal number of successes and failures, viewed on the multi-cluster view:

![Screenshot from 2020-11-09 16-09-07](https://user-images.githubusercontent.com/5208768/98596884-1b211300-22a6-11eb-8668-7512a4552c84.png)

Cluster data with an equal number of sucecsses and failures, viewed on a single-cluster view:

![Screenshot from 2020-11-09 16-09-25](https://user-images.githubusercontent.com/5208768/98596944-368c1e00-22a6-11eb-9cad-db7697cf69ba.png)

Ideally we'd be able to note this better in the second graph other than the successes popping up in the tooltip only.

**Desktop (please complete the following information):**
 - OS: Linux
 - Firefox 82.0.2

**Comment by kialam** [comment]
This is a case where https://github.com/RedHatInsights/tower-analytics-frontend/issues/344 (interactive tooltips) would come in handy.

**Comment by benthomasson** [comment]
How about dashed lines for overlapping lines here?
