### ISSUE TITLE
Templates Explorer

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#352]
# Description

Templates Explorer shows a list of templates with drill down and details of those templates.

**Is your feature request related to a problem? Please describe.**

Customers want to be able to drill down further into templates similar to Top 5 Templates but they want to see all the details of that template.  

**Describe the solution you'd like**

A new left nav item that shows a list of templates with links to detail pages.

**Describe alternatives you've considered**

Using the job explorer with user training.  We don't have a good way to do user training right now.  Pendo might work.  A self-evident UI would be better.

**Additional context**

**Mock up**

https://tower-mockups.testing.ansible.com/analytics/templates/analytics-templates/

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-196
