### ISSUE TITLE
Browser's back button behaviour with filters change

### ISSUE THREAD

**Issue by brumik** [RedHatInsights/tower-analytics-frontend#354]
@trahman73 @benthomasson @kialam @jctanner 
I didn't get a definitive answer yet so...:

What is the expected behaviour when using the browser's back button on a page where there is a filter?
1. Go back to the previous page
2. Go back to the previous filter state

In the case of 2. option, we need to synchronize the `history` and the `queryParams`.

**Comment by benthomasson** [comment]
In general we should go to the previous filter state.  Except for the initial state of page should go to the previous page.  If the implementation adds filter states after landing on a page those states should be ignored for the purpose of the back button.

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-197
