### ISSUE TITLE
View all jobs link broken

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#356]
**Describe the bug**
Clicking on the "View all jobs" link from the top templates modal no longer works.

**To Reproduce**
1. Go to 'https://cloud.redhat.com/beta/ansible/automation-analytics/clusters'
2. Click on a top template to open the modal.
3. Click on 'View all jobs' link.
4. Observe that it takes you to a blank page.

**Expected behavior**
The 'View all jobs' link should take you to the Job Explorer page.

**Screenshots**
![view_all_jobs](https://user-images.githubusercontent.com/2293210/99683643-9032dc00-2a4e-11eb-891b-f12d8f740508.gif)

**Comment by brumik** [comment]
@kialam I cannot reproduce exactly this bug locally on the `devel` branch. I did found that the redirects not work, where there was required an array and only a single value was passed, however, I believe it was introduced later and I don't see how would create this issue. (https://github.com/RedHatInsights/tower-analytics-frontend/pull/357)

Can you recreate this issue locally?

**Comment by kialam** [comment]
@brumik this is reproducible on prod beta. @benthomasson looks like prod beta is behind the current `devel` branch by quite a few commits?

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-198
