### ISSUE TITLE
Toolbar multiselect closing after checking one

### ISSUE THREAD

**Issue by brumik** [RedHatInsights/tower-analytics-frontend#358]
The toolbar multiselect is closing when changing a value. This is due to the whole page component is rerendering. It is done with the fact that when we change a filter we set the `loading` state. This rerenders the whole page, including the toolbar, since the page is not a pure component (and I am not sure that would solve it or it is possible to make the page component pure component). 

I have no idea how could we solve this issue yet.

Any ideas: @kialam @benthomasson @jctanner @jeanetteobr

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-199
