### ISSUE TITLE
Toolbar filter category renders category with no selection

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#377]
**Describe the bug**
The Filter Toolbar renders categories that no longer exist.

**To Reproduce**
Depending on the order of the `categories` object, this can lead to the logic of determining the `currentCategory` to be a category that gets filtered out later (e.g. quickDateRange & sortBy).

**Expected behavior**
Categories should have selections.

**Screenshots**
![category_no_dropdown](https://user-images.githubusercontent.com/2293210/102255430-1587a000-3ed8-11eb-8908-be36bdb66ee8.gif)

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-201
