### ISSUE TITLE
Time dependent unit tests fail at 7:48 pm ET

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#381]
FAIL  src/Utilities/useQueryParams.test.js
  Utilities/useQueryParams
    ✓ returns expected initial values as queryParams  (75 ms)
    ✓ returns setId, setStartDate, setEndDate, and setLimit as methods (7 ms)
    ✓ invoked methods returns new queryParams object (4 ms)
    ✓ setId, setLimit correctly handles null, undefined and NaN values (5 ms)
    ✕ setEndDate returns current day in `YYYY-MM-DD` string format (22 ms)
    ✕ setStartDate returns current day if passed a null value (19 ms)
    ✕ setStartDate returns expected day when invoked (29 ms)

**Comment by benthomasson** [comment]
This is 12:48 am UTC

**Comment by jctanner** [comment]
I'm going to attempt to reproduce this failure.

**Comment by jctanner** [comment]
Setting the expected value with `const currentDate = moment(new Date().toISOString()).format('YYYY-MM-DD');` does not resolve the issue.

**Comment by jctanner** [comment]
The changes in https://github.com/RedHatInsights/tower-analytics-frontend/pull/383 do appear to resolve the issue.

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-202
