### ISSUE TITLE
As an AI user, I want to visualize job runs in relation to my available clusters

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#4]
An AI user should be able to see the following:

- [x] total # of job runs across all clusters as represented by a bar chart.
- [x] total # of job runs across certain clusters as represented by a line chart.
- [x] charts should show a tooltip on hover with correct information:
    1. date
    2. total # of job runs
    3. total # of failed jobs
    4. total # of successful jobs
- [x] charts should update according to the date range selected.
- [ ] charts should update according to the accessibility toggle.

### Job Run Chart
- [x] On the AA Dashboard, I should see a graph of total # of job runs
- [x] On the AA Dashboard, I should see a graph of total # of job runs which can be represented as a bar chart
- [x] On the AA Dashboard, I should see a graph of total # of job runs which can be represented as a line chart
- [ ] On the AA Dashboard, I should be able to toggle between bar to line charts without losing context of filtered/restricted views (this could be time range or selected Orgs)
- [x] On the AA Dashboard, I should see a graph of total # of job runs which can be represented as a bar chart
- [x] On the AA Dashboard, I should be able to modify the date range of data
- [x] After Refresh, On the AA Dashboard, I should see the same date range of data

### Hoverover Tooltip
- [x] When hovering over a datapoint on the chart, I should see the following information
-- 1. date
-- 2. total # of job runs
-- 3. total # of failed jobs
-- 4. total # of successful jobs
-[ ] <Insert Standard hoverover actions here>
- [ ] Hoverover extreme value
- [x] Hoverover 0 value
@kialam what about organization

### Accessibility
- [ ] I should be able to modify accessibility for the default chart with a toggle
- [ ] I should be able to modify accessibility for the default chart with a toggle with a modified view (date range)

### Extreme value differences
With a dataset of Job Run 10000 Jobs on Day 10 and 0 Jobs on Day 0
- [ ] Data should be legible on graph

**Comment by unlikelyzero** [comment]
https://github.com/RedHatInsights/tower-analytics-frontend/issues/15

**Comment by kialam** [comment]
Released in 1.0.0
