### ISSUE TITLE
Need to do some cleanup of code that sets up errors returned from API calls

### ISSUE THREAD

**Issue by h-kataria** [RedHatInsights/tower-analytics-frontend#453]
This is not really a bug as such, just an issue to clean up and to be consistent with new screens so the `preflightError` is stored in the same way everywhere. Makes it easier to redirect/render components to display error messages.
Noticed this while working on https://github.com/RedHatInsights/tower-analytics-frontend/pull/452

Example of this patters is 
https://github.com/RedHatInsights/tower-analytics-frontend/blob/devel/src/Containers/Clusters/Clusters.js#L174-L176 vs https://github.com/RedHatInsights/tower-analytics-frontend/blob/devel/src/Containers/OrganizationStatistics/OrganizationStatistics.js#L225-L227

**Comment by brumik** [comment]
@h-kataria Is this issue in JIRA? If not we should put it there and close it for consistency. If it is already there can you close this?

**Comment by h-kataria** [comment]
closing this in favor of https://issues.redhat.com/browse/AA-498
