### ISSUE TITLE
RFE: be able to inspect UI and know what version is

### ISSUE THREAD

**Issue by kdelee** [RedHatInsights/tower-analytics-frontend#48]
We discussed how we would like to make the tests version aware, so we can handle roll backs as well as writing tests in advance so the tests skip until the new feature or bugfix is deployed.

Idea would be there would be some hidden tag or element that reported the version. We would want this element to be present on every page of the app and have a unique css locator grab it. Then it should contain a text string of the version, which should be something we can parse and do version comparisons on. E.g. it needs to be `x.y.z` or date based...I'm thinking `x.y.z` would be easier for us.

**Comment by unlikelyzero** [comment]
This is already available on the info page to some degree
