### ISSUE TITLE
As an AI user, I want to see a list of top modules across all clusters

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#6]
An AI user should see:
- [x] A list of top templates with the following layout:
    - module name
    - module usage count

### Dashboard Module Table
- [x] On the AA Dashboard, I should see the table of the 5 most used Modules sorted by use over <Time Period>
- [x] On the AA Dashboard, I should see the table of the most used Modules and associated number of uses
- [x] The Module Table should display the same data if refreshing the page
- [x] The list of Modules is updated every <Duration?>
- [x] If no Modules have been run then 5 empty rows are displayed
- [x] The Module list shows data from multiple organizations and clusters

**Comment by elyezer** [comment]
This has been done a long time ago and I missed updating the issue properly. Time to get it finally closed.
