### ISSUE TITLE
Memory leak when toggling between Bar Chart and Line Chart components in Clusters View

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#64]
Toggling between line and bar chart generates errors in the console.
![toggle_bug](https://user-images.githubusercontent.com/2293210/73952437-e9b98800-48cc-11ea-88ea-37817888d24a.gif)

There is likely a memory leak somewhere - we are trying to setState on an unmounted component. I would consider this a blocker prior to releasing https://github.com/RedHatInsights/tower-analytics-backend/issues/40

**Comment by kdelee** [comment]
@kialam can you explain how to observe the memory consumption? Should I look at the pod stats or can I see this in chrome?

**Comment by kialam** [comment]
Steps to reproduce: 
In the Clusters view, while having the chrome dev console open, attempt to toggle the dropdown that switches from "All Clusters" to specific clusters. This should trigger the mounting/un-mounting of the bar and line charts. You should then see console errors to the effect of ```TypeError: Cannot read property 'style' of null``` as well as ```Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.```

**Comment by kdelee** [comment]
I can confirm this message is not appearing after a good deal of switching between line and bar charts. Calling this verified
