### ISSUE TITLE
Convert card titles to sentence case

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#65]
# Description

TODO: Need to convert card titles (e.g. Top Templates) to sentence case (Top templates).
See [here](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/card-view) for further details.

# Verification
 Check that the case is correct in these locations:
* Automation calculator title
* Organization statistics
* Organization status
* Job runs by organization
* Usage by organization (tasks)

**Comment by benthomasson** [comment]
We should expand this to everything except "Automation Analytics" or user generated strings.

**Comment by kialam** [comment]
Agreed 💯

**Comment by jctanner** [comment]
Resolved by https://github.com/RedHatInsights/tower-analytics-frontend/pull/154

**Comment by benthomasson** [comment]
@jctanner please update the description with the locations where the case has changed so that QE can check it quickly.

**Comment by jctanner** [comment]
https://github.com/RedHatInsights/tower-analytics-frontend/pull/162

**Comment by appuk** [comment]
verified that all the titles are in sentence case 👍
