### ISSUE TITLE
Requests to /template_jobs/id endpoint are missing date ranges

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#68]
Need to specify `startdate` and `enddate` params for requests to `/template_jobs/id`. Otherwise the job counts do not match.

<img width="326" alt="1count" src="https://user-images.githubusercontent.com/2293210/74241176-79827c00-4ca9-11ea-8eaa-6bc7c66b65bc.png">
<img width="291" alt="2count" src="https://user-images.githubusercontent.com/2293210/74241178-79827c00-4ca9-11ea-9dea-29e66162f6bc.png">

**Comment by kdelee** [comment]
verified! 
![Screenshot from 2020-02-18 14-55-06](https://user-images.githubusercontent.com/29239279/74775165-25f0cf00-5263-11ea-84d0-efc08c89c96a.png)
