### ISSUE TITLE
As an AA user, I want to see a list of notifications across all clusters on the Dashboard

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#7]
An AA user should see:
- [ ] A list of 5 of the most recent notifications with the following layout:
    - icon/badge if notification type is danger or warning
    - notification message/detail

An AI user should sort by notification type via the dropdown.

Question: should the sorting of the lists be based on timestamp or notification type?

### Dashboard Notification Table
- [ ] On the AA Dashboard, I should see the table of the 5 most recent notifications sorted by <Date?>
- [ ] The Notification Table should display the same data if refreshing the page
- [ ] The Notification should display a icon/badge for a warning notification
- [ ] The Notification table should display a icon/badge for an error notification
- [ ] The Notification Table Detail should not word wrap for longer strings.
- [ ] The Notification Table Detail should display 128 characters of a notification text with ellipsis.
- [ ] The Notification Table should display the same data if cycling between dropdown filters and back to "all"
- [ ] The Notification Table should display only (up to) 5 warnings if Warning dropdown is selected
- [ ] The Notification Table should display only (up to) 5 errors if Errors dropdown is selected
- [ ] The list of notifications is updated every <Duration?>
- [ ] If no notifications exist, then 5 empty rows are displayed.
- [ ] The notification list shows data from multiple organizations and clusters

### Precedence Case A
- Single or Multi-tower-cluster
- 10 total notifications
- 6 warnings
- 3 dangers
- 1 standard
- [ ] When viewing the dataset above, the initial table only displays 3 dangers and 2 warnings. 
- [ ] When using the dropdown filter for Warnings, only the 5 most recent warnings are shown.
- [ ] When using the dropdown filter for Errors, only 3 errors are shown.
- [ ] When using the dropdown filter for All after warnings/Errors, the initial set of notifications are shown.

### Precedence Case B
- Single or Multi-tower-cluster
- 10 total notifications
- 2 warnings
- 2 dangers
- 6 standard
- [ ] When viewing the dataset above, the initial table only displays 2 dangers, 2 warnings, and 1 regular. 
- [ ] When using the dropdown filter for Warnings, only the 2 most recent warnings are shown.
- [ ] When using the dropdown filter for Errors, only 2 errors are shown.
- [ ] When using the dropdown filter for All after warnings/Errors, the initial set of notifications are shown.

### User Scenario - Fix Notification
- [ ] A user sees a Warning notification. User goes onto the Tower to “fix” the notification, goes back to the dashboard. How long does it take to the dashboard to update?

**Comment by unlikelyzero** [comment]
In the following scenario:

- 15 total notifications
- 6 warnings
- 3 dangers
- 6 regular warnings

What should be shown for the top 5 returned? Is it the first 5 of by time?
What should be shown when the table view is constricted to warnings?

**Comment by kialam** [comment]
Blocked until we can get a staging environment with mocked or working data up and running.

**Comment by wenottingham** [comment]
There should be a way to get all warnings/etc; you don't want to "lose" data, effectively.

**Comment by unlikelyzero** [comment]
@wenottingham does that need to be displayed on that same dashboard?

**Comment by wenottingham** [comment]
Can be a popout if needed.

**Comment by unlikelyzero** [comment]
I think that needs to be a separate feature card @kialam

**Comment by kialam** [comment]
Released with 1.0.3
