### ISSUE TITLE
Handle expiring tokens in the UI

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#70]
We should be calling `insights.chrome.auth.getUser()` before each API request to refresh the user token if necessary.

**Comment by benthomasson** [comment]
What happens if we do not do this?

**Comment by kialam** [comment]
I think the API returns 401 not authorized

**Comment by benthomasson** [comment]
OK before each batch of API calls we should call that function.

**Comment by kdelee** [comment]
1) Open session
2) Leave open for 15 min
3) Change filter without refreshing

**Comment by kdelee** [comment]
I followed steps outlined above ^ and I see that the token gets refreshed and I am successfully able to change the filters without having to do hard refresh of whole page. Calling this verified
