### ISSUE TITLE
Do not include tower cluster link in notifications where it does not apply

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#74]
<img width="416" alt="Screen Shot 2020-02-19 at 9 22 12 AM" src="https://user-images.githubusercontent.com/44381/74843198-964a2f80-52f9-11ea-8f8b-ac8e22bf9832.png">

![Screen Shot 2020-02-19 at 9 23 34 AM](https://user-images.githubusercontent.com/44381/74843280-afeb7700-52f9-11ea-8a50-3e2a5de8075a.png)

When `tower_url` is `null` we should not show the link out.

**Comment by kdelee** [comment]
This is now deployed to QA/beta and is working! :dancer: 
![Screenshot from 2020-02-20 11-44-41](https://user-images.githubusercontent.com/29239279/74958197-91a77900-53d6-11ea-9973-dc42bb8a70e4.png)
