### ISSUE TITLE
Seeing console error "a negative value is not valid"

### ISSUE THREAD

**Issue by kdelee** [RedHatInsights/tower-analytics-frontend#76]
Trying to reproduce this again, but while verifying https://github.com/RedHatInsights/tower-analytics-frontend/issues/64 I noticed a long string of the following error:

![Screenshot from 2020-02-19 13-15-24](https://user-images.githubusercontent.com/29239279/74862953-074e0f00-531b-11ea-997b-c9557bc14c63.png)

**Comment by jctanner** [comment]
@kdelee can you confirm this was fixed by the commits above?

**Comment by wenottingham** [comment]
cc @appuk

**Comment by appuk** [comment]
This seems to be resolved
