### ISSUE TITLE
Explain we are only showing last 5 job runs for top playbooks etc

### ISSUE THREAD

**Issue by kdelee** [RedHatInsights/tower-analytics-frontend#77]
![last5runsthing](https://user-images.githubusercontent.com/29239279/74877323-44be9680-5333-11ea-8ad2-399d04c5301e.png)

When looking at this it is a bit confusing when you have more than 5 runs, but only 5 show, especially because the number of runs in showed in the grey area. I suggest some small div below that says "Last five runs" or something like that

**Comment by kdelee** [comment]
thinking this would be for 1.0.2 whenever we start tracking that w/ a project

**Comment by jctanner** [comment]
reopening for testing

**Comment by appuk** [comment]
I can now see the last N jobs header in the template modal, hence closing 👍 
<img width="1337" alt="Screen Shot 2020-07-08 at 12 27 11 PM" src="https://user-images.githubusercontent.com/11617351/86944888-5d7aed80-c116-11ea-90fc-a3363d3a0fe8.png">
