### ISSUE TITLE
store that state in the url (e.g. when do hard refresh, reload with same filters as were previously set)

### ISSUE THREAD

**Issue by kdelee** [RedHatInsights/tower-analytics-frontend#79]
Right now if you are on, for example, the orgs page and you set the "Bottom 5 Orgs" filter and then do a hard refresh, you return to the orgs page but with the "Top 5 Orgs" which is the default filter.

@benthomasson suggested we could store the state in the url (e.g. what filter we were looking at) so when we do a hard refresh, we return to same view w/ same filter.

This would apply to the clusters view as well.

**Comment by benthomasson** [comment]
This may be fixed by  #353

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-145
