### ISSUE TITLE
Left nav bar item highlighted does not update when using back buttons

### ISSUE THREAD

**Issue by kdelee** [RedHatInsights/tower-analytics-frontend#80]
Say I am on Clusters page. in the left nav bar Clusters is highlighted. If I then navigate to the Organizations page with left nav, now Organization statistics is highlighted. If I then click back bar, clusters page displays but Organization statistics is still highlighted

@ryelo says "You may have to add a listener to your routes to update it"

![sidebar_hightlight_does_not_move_on_back_navigate](https://user-images.githubusercontent.com/29239279/74966128-7f343c00-53e4-11ea-9859-521d3ae4eff1.gif)

**Comment by jctanner** [comment]
This issue spans across all apps on the insights platform. I see it in the automation hub nav items and throughout the various apps on the /insights route. It may not be something we can sufficiently fix in our app, although we can call insights.chrome.appNavClick whenever a component is loaded, the mouse hover over highlight does not go away leading to a weird mix of one app being selected and another hovered over until the user clicks somewhere in the UI.
