### ISSUE TITLE
Orgs should share colors in different charts if they are in multiple charts

### ISSUE THREAD

**Issue by kdelee** [RedHatInsights/tower-analytics-frontend#81]
noticing that the colors used across charts for same org is not consistent
For example, MasterReputation goes from a UNC Blue, to blue-green, to mustard yellow

![Screenshot from 2020-02-20 13-33-51](https://user-images.githubusercontent.com/29239279/74969014-db4d8f00-53e9-11ea-971f-10cff6e0e3ba.png)
![Screenshot from 2020-02-20 13-33-40](https://user-images.githubusercontent.com/29239279/74969024-dee11600-53e9-11ea-9d30-6d9a39f0501d.png)

some responses when discussing this:
```
1:41 PM
Corey Welton that's weird
1:41 PM
kialam:speech_balloon: @notting noticed this to. it has to do with the order in which the orgs get returned from the API
1:42 PM
so with 3 separate endpoints, each endpoint can return [orga, org b, orgc], [orgc, orga, orgb], etc.
1:43 PM
the color palette is an array of hex values and we just loop through the orgs and assign it by index value
1:43 PM
this might be worth making an orgs endpoint however, where the UI can query for all the orgs, assign it a color, and then make charts; i dunno
```

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-146
