### ISSUE TITLE
Org selection should be preserved across time filter changes

### ISSUE THREAD

**Issue by kdelee** [RedHatInsights/tower-analytics-frontend#82]
![org_selection_does_not_persist_after_time_filter_change](https://user-images.githubusercontent.com/29239279/74969994-99bde380-53eb-11ea-9abd-ac36f8847b0b.gif)

downselect orgs then change time filter, (this is with all orgs), expected that my selection would stay valid -- if orgs selected do not have data for that time period, show all orgs disabled, allow user to change org selection

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-147
