### ISSUE TITLE
Add cache busting so new code gets deployed to all users when it is released.

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#84]
During a customer feedback meeting a customer was still running old code 4 days after it was released.  I had to ask them to shift-reload to get the new code.   We should implement file name hashing on the bundle to fix this.

Our bundle looks like this: https://cloud.redhat.com/apps/automation-analytics/js/automation_analytics.js

It should be something like this:  https://cloud.redhat.com/apps/automation-analytics/js/automation_analytics.ABCD123.js

**Comment by benthomasson** [comment]
How to verify:

1. Go to the web interface https://ci.cloud.redhat.com/apps/automation-analytics
2. Right click on the background
3. Select inspect element
4. Go to the network tab
5. Hard reload the page
6. Look for a request to https://ci.cloud.redhat.com/apps/automation-analytics/App.591439e79f6ce138c24a.js  where 591... might be some other hash.

**Comment by benthomasson** [comment]
I pushed this fix to ci-beta, qa-beta, ci-stable, and qa-stable.

**Comment by kdelee** [comment]
@benthomasson I have confirmed on ci-beta, qa-beta, and qa-stable that I get the files w/ hashes!

```
/beta/apps/chrome/js/App.03338c47.css
/beta/apps/chrome/js/App.1c9bfc85.js
beta/apps/automation-analytics/js/automation_analytics.7400235cdf8b09c5418a.js
```

Thanks for clear instructions + noting where the fix was deployed. LGTM!

**Comment by kdelee** [comment]
This is ready to deploy from my perspective, no backend changes needed

**Comment by benthomasson** [comment]
This fix is live on production.
