### ISSUE TITLE
Notifications do not show all of the items due to pagination.

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#87]
It only shows 10 due to pagination in the api.   Also there is a array slice in the UI that only shows 10.

![Screen Shot 2020-03-06 at 12 12 39 PM](https://user-images.githubusercontent.com/44381/76106074-2055f180-5fa4-11ea-81c1-eb9e36b7359b.png)

**Comment by benthomasson** [comment]
Customers are not hitting this yet with the few number of notifications rules that we have.   When we add more they will hit it.   We can roll out the new notifications UI instead of fixing this in the current view.

**Comment by kialam** [comment]
With 1.0.3 and the new Notifications view #72 this is no longer an issue for customers.
