### ISSUE TITLE
Adjust full page empty state styling

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#92]
# Description

Our full page empty state styling needs to be updated in order to conform with Patternfly design guidelines. Currently it looks like this:
![image (5)](https://user-images.githubusercontent.com/2293210/77943358-19608d00-728b-11ea-9caa-3ef1cdcb7c70.png)

We need to:
1. Change in icon (wrench for this example)
2. No period in header
3. Make header sentence case
4. No card background on a full page empty state

See [Updated PF Empty State Guidelines](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/empty-state/) for more details.

# Verification

![Screen Shot 2020-04-03 at 11 00 53 AM](https://user-images.githubusercontent.com/32466511/78375506-df4cff00-759a-11ea-8688-fb29d76c172c.png)

For Clusters view, Org Stats view, and Notifications view, ensure:
* Check the icon
* Check for no period in header
* Check for sentence case
* Gray background

**Comment by appuk** [comment]
🎉 
![empty-state](https://user-images.githubusercontent.com/11617351/80121156-f2c80600-8559-11ea-91a5-1c766f505c91.gif)
